US-Trustee-Program/Bankruptcy-Oversight-Support-Systems

.github/workflows/continuous-deployment.yml
Runs the deploy depending on branch.
=> 111: Only run deploy on one branch

README.md, decision-records/ApiTechnology.md
Add an ADR documenting our backend comparison and decision.
Modify README.md to reflect the final decision on the API.
=> Document backend decision

.github/workflows/continuous-deployment.yml, backend/functions/lib/adapters/services/logger.service.ts, ops/helper-scripts/sec-update-baseline.sh
**Description of changes**
- Update to usage of pipeline-scan.jar to execute SAST scan
- Leverage baseline file to filtered known findings to ignore
- Include bash script to upload updated baseline file to Azure storage account 
Validation
- Verified filtered findings provided by baseline and passing pipeline scan in CI pipeline
- Verified local execution of helper script to update baseline
=> CAMS-20 Implementation of pipeline-scan with baseline file

.github/workflows/continuous-deployment.yml, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/frontend-webapp-deploy.bicep, ops/cloud-deployment/ustp-cams.bicep
Parametrized AZ_PLAN_TYPE variable to pass into bicep files allowing deployment on main and development branches with their corresponding SKUs for frontend and backend components.
=> CAMS-64 parameterized AZ_PLAN_TYPE in main bicep file

.github/workflows/continuous-deployment.yml, ops/helper-scripts/azure-deploy.sh
This branch began as a test for the fix. Discovered that some of the conditionals were not being evaluated as expected. This PR corrects the functionality and renames the `--resourceGroup` option for `azure-deploy.sh` to be in line with the related `--resource-group` option on Azure CLI commands.
=> CAMS 64 Testing

backend/functions/lib/adapters/gateways/pacer.api.gateway.test.ts
Finish up testing the PACER environment variables.
=> Cams 37 get unassigned chapter 15 case list

.github/workflows/continuous-deployment.yml, .secrets.baseline, ops/helper-scripts/dev-add-allowed-ip.sh, user-interface/public/index.html
Feedback Loop tested and seems to be working.  We'll need to verify that the submission was received by Jira, but everything in the UI seems to be working, and UI says the submission of form was successful.
=> Cams 15 user feedback loop

user-interface/src/components/CaseAssignment.test.tsx, user-interface/src/components/CaseAssignment.tsx
Chapter 15 list should now be displaying properly.
=> Cams 9 fix chapter 15 list

user-interface/src/components/CaseAssignment.tsx
Sorting was backwards for chapter 15 on the front end.  Fixed sorting.
=> CAMS-95: Fixed sorting

.github/workflows/continuous-deployment.yml
Enable code build and deployment from code changes in a branch. Adding workflow dispatch will also allow us to trigger CICD pipeline without need for code commit.
- Updated GHA deployment script to include workflow_dispatch
- Add rule to ignore changes on md file to prevent pipeline execution
- After this change has been merged into main, there should be an option to `Run Workflow` to trigger the pipeline with specified parameters.
This pull request will need to be merged into the main branch before it could take into effect.
=> CAMS-53 Manual trigger to enable branch deployment

.github/workflows/continuous-deployment.yml, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/frontend-webapp-deploy.bicep, ops/helper-scripts/az-app-deploy.sh, ops/helper-scripts/az-func-deploy.sh, user-interface/src/ApplicationInsightsService.tsx
Merging in experimental updates tested on separate environment
- Update backend and frontend bicep to enforce required dependency
- Parameterized app insights connection string for frontend
- Confirm instrumentation key include in frontend build artifact
- Success bicep deployment
=> CAMS-103 Additional updates to frontend App Insights

docs/architecture/decision-records/FrontendBuildTooling.md, docs/architecture/decision-records/FrontendDesignSystem.md, docs/architecture/decision-records/_sidebar.md
Document recent decisions regarding frontend tech stack.
Adds two decision records addressing build tooling and design system.
=> CAMS-47 ADRs

.github/workflows/continuous-deployment.yml, ops/helper-scripts/json-parser.py
Additional updates to support latest USTP deployment from main
- Include python script to help parse bicep OUTPUT json file
- Update env reference name for CosmosDb diagnostic settings
- Run branch deployment in USTP environment
=> CAMS-130 USTP deployment updates

.github/workflows/continuous-deployment.yml, ops/cloud-deployment/app-insights/diagnostics-settings-appi.bicep, ops/cloud-deployment/app-insights/diagnostics-settings-cosmos.bicep, ops/cloud-deployment/app-insights/diagnostics-settings-func.bicep, ops/cloud-deployment/app-insights/diagnostics-settings-webapp.bicep, ops/helper-scripts/json-parser.py
removal of deprecated retention policy on diagnostic settings
removal of diagnostics settings retention policies on each of the templates
ran a full deployment on a development environment to test creation of the diagnostic setting resources without issue
=> Cams 130 ustp deployment

.github/workflows/continuous-deployment.yml, .secrets.baseline, docs/running.md, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/ustp-cams.bicep
PACER is no longer in use and we do not need the Azure resources for it.
Removes PACER resources and variables.
Deployed manually [here](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/6161006641).
=> CAMS-83 Remove implementations related to integrating Pacer api

docs/_sidebar.md, docs/deployment.md
Document CI/CD vars and secrets for deployment closer to the code
Addition of .md for documentation of CI/CD pipeline vars and secrets 
N/A
This will need to be updated any time changes are made to the secrets/vars
=> CAMS-137 document updates to secrets and env vars

architecture/cams.dsl, docs/architecture/diagrams/cams-containers.md, docs/architecture/diagrams/cams-functions-api-components.md, docs/architecture/diagrams/cams-webapp-with-functions-api.md, docs/running.md
Update documentation for definition of done.
- Add the Attorneys Function to the diagrams.
- Add instructions for running Docsify locally.
Ran Docsify locally to validate changes.
=> CAMS-47: DOD - Update Documentation

backend/functions/case-assignments/case.assignment.function.test.ts, backend/functions/case-assignments/case.assignment.function.ts, backend/functions/lib/adapters/controllers/case.assignment.controller.test.ts, backend/functions/lib/adapters/controllers/case.assignment.controller.ts, backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.test.ts, backend/functions/lib/adapters/gateways/case.assignment.local.repository.test.ts, backend/functions/lib/adapters/types/basic.d.ts, backend/functions/lib/adapters/types/case.attorney.assignment.ts, backend/functions/lib/factory.ts
Continue with definition of done refactoring
- Move business logic to controller class and update test according to change.
- All test passing and verified running application locally
=> CAMS-47 dod refactor

ops/helper-scripts/az-func-deploy.sh
There was a concern with the CAMS functionapp deployment script, `az-func-deploy.sh`, where multiple calls to update app settings may cause the scm container restart because of management operations. Reducing the number of request via the az cli is also desired.
- Update script to make a single call to config app settings
- Update query to display name of app settings
- Local testing to confirm scripts works as expected to deploy backend code.
- Verified no secrets outputted to standard out
- Verified all the above again in branch deployment
=> CAMS-144 improve func app deploy

backend/functions/host.json
Purpose of this change is to extend the logging to capture more useful information from the functions
Modification to host.json to extend log levels
deployed to a development environment and went through the logs to see what was being capture from the new settings
We can also start capturing custom logs if we would like to go down that path
=> CAMS-142: increase log levels

user-interface/src/components/CaseDetail.scss, user-interface/src/components/CaseDetail.test.tsx, user-interface/src/components/CaseDetail.tsx, user-interface/src/type-declarations/chapter-15.d.ts
Staff assignments were not displaying on the case details screen as expected.
Modify CaseDetail.tsx to display staff assignments properly.
Update automated tests and validate in the UI locally.
=> CAMS-164 display assignments

user-interface/src/components/CaseDetail.scss, user-interface/src/components/CaseDetail.tsx, user-interface/src/components/uswds/Icon.tsx, user-interface/src/models/chapter15-mock.api.cases.ts
Add Back Button to return to case assignment screen from case detail.
Link added and USWDS Icon component created.
Testing coverage did not change.
=> CAMS-189: Added Back button and Icon uswds component

user-interface/package-lock.json, user-interface/src/components/AssignAttorneyModal.scss, user-interface/src/components/AssignAttorneyModal.test.tsx, user-interface/src/components/AssignAttorneyModal.tsx, user-interface/src/components/uswds/Checkbox.scss, user-interface/src/components/uswds/Checkbox.tsx, user-interface/src/components/uswds/Icon.tsx, user-interface/src/components/uswds/modal/Modal.tsx, user-interface/vite.config.ts
Add LaunchDarkly Feature Flag for changing text label in Assign Attorneys modal.
Added feature flag handling to modal.  Additionally, updated code to handle USWDS icons so that the build process properly moves images to assets folder, and JSX accesses icons from assets folder.
Tests have been written and coverage on lines is around 91%.
=> CAMS-196 feature flag modal label change

.github/workflows/continuous-deployment.yml
Issue with backend not updating according to Launch Darkly feature flag
- Add new secret to GHA to include sdk key
- Update deployment script to set app settings for sdk client for backend
- Verified with manual updates to the app settings for backend
=> CAMS-193 Set feature flag sdk to backend

.github/workflows/continuous-deployment.yml
New package was added that needs to be included as part of the Veracode SCA scan.
- Add new CI job execution
- New job ran successfully. Verified path to /common
=> CAMS-193 Execute SCA for new common package

common/src/feature-flags.d.ts, user-interface/package-lock.json, user-interface/package.json, user-interface/src/App.scss, user-interface/src/components/uswds/Alert.scss, user-interface/src/components/uswds/Icon.tsx, user-interface/src/components/uswds/modal/Modal.tsx, user-interface/vite.config.ts
Jira ticket: CAMS-197
Fonts were not being referenced correctly in the css.
I resolved this by having the build copy the USWDS fonts over to the expected directory.
In the process I noticed that the images could be loaded the same way, and by making the switch, the image use for the sprite can be simplified.  Therefore I also updated the way images are copied on build.  The result is that all images from uswds are now included, as well as all fonts.  This may be seen as a bad thing if we do not need to utilize all of those images.  This can be refined later if need be.
We may not need any testing for this.
=> CAMS-197: Fixed font loading issues, optimized image load

backend/functions/lib/adapters/gateways/cases.dxtr.gateway.test.ts, backend/functions/lib/adapters/gateways/cases.dxtr.gateway.ts, backend/functions/lib/adapters/gateways/cases.local.gateway.ts, backend/functions/lib/adapters/types/cases.d.ts, backend/functions/lib/adapters/utils/date-helper.test.ts, backend/functions/lib/adapters/utils/date-helper.ts, backend/functions/lib/adapters/utils/http-client.test.ts, backend/functions/lib/testing/mock-data/cases.mock.json, user-interface/src/components/CaseDetail.test.tsx, user-interface/src/components/CaseDetail.tsx, user-interface/src/components/uswds/modal/SubmitCancelButtonGroup.tsx, user-interface/src/type-declarations/chapter-15.d.ts
Add reopen date presentation logic to case detail.
* Expose reopen date in case detail from API.
* Consume reopen date in UI.
* Add reopen date presentation logic in case detail view.
* Unit tests written.
* Manually tested multiple reopen/close/dismissed conditions in DEV database.
=> CAMS-186 view reopened date

ops/helper-scripts/az-app-deploy.sh, ops/helper-scripts/az-func-deploy.sh, ops/helper-scripts/dev-add-allowed-ip.sh
--retry-all-errors option not available in USTP environment
- Update curl options to work in both Flexion and USTP
- Verify updates in local environment
- Verify updates in USTP pipeline
=> CAMS-192 update curl options to work with USTP deployment

dev-tools/package-lock.json, dev-tools/package.json, dev-tools/test-data/scripts/index.ts
We moved index.js to a subfolder and forgot to update the imports. we also didn't add faker to package.json
Added Faker and fixed index imports.
=> CAMS-181:  Small fix for something we broke in the dev-tools

dev-tools/README.md, dev-tools/test-data/scripts/updateCasePartyAddresses.ts, dev-tools/test-data/tables/AO_PY.ts, dev-tools/test-data/utility.ts
Script the ability to update debtor addresses in the database.
Added a script to specifically regenerate fake address values in the AO_PY table.
Visually inspected SQL UPDATE statements, executed against the DB and used SELECT statement to confirm expected results.
=> CAMS-182 Debtor address test data

backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/adapters/types/cases.d.ts, backend/functions/lib/adapters/utils/string-helper.test.ts, backend/functions/lib/adapters/utils/string-helper.ts, ops/git-setup/prepare-commit-msg, package.json, user-interface/src/components/CaseDetail.scss, user-interface/src/components/CaseDetail.test.tsx, user-interface/src/components/CaseDetail.tsx, user-interface/src/type-declarations/chapter-15.d.ts
Display Tax ID for companies and or SSN/ITIN for individuals 
Added taxId and ssn to dxtr query in the back end.
Added ADDITIONAL DEBTOR INFORMATION section to front end to display tax info.
Testing coverage for backend is 93%.
Testing coverage for front-end: 91%
=> CAMS-185 view tax ids

backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/adapters/types/cases.d.ts, backend/functions/lib/testing/mock-data/debtor-attorneys.mock.ts, docs/running.md, user-interface/src/components/CaseDetail.test.tsx, user-interface/src/components/CaseDetail.tsx, user-interface/src/models/chapter15-mock.api.cases.ts, user-interface/src/type-declarations/chapter-15.d.ts
Jira Ticket: CAMS-205
Addition of the Debtor Attorney email to the Case Detail Screen within the applciation
- addition of debtor attorney email to api
- addition of debtor attorney email to user interface
- tests written validating email both front and backend
- additional test validating href link
- ran application locally and validated changes
- ran coverage and accessibility
=> CAMS-205 Added debtor attorney email with corresponding tests

user-interface/src/components/AssignAttorneyModal.test.tsx, user-interface/src/components/AssignAttorneyModal.tsx, user-interface/src/components/CaseAssignment.tsx
Jira Ticket: CAMS-215
Assign Attorney button on case would not pop modal on a second assignment
Corrected the modal state to allow the modal after first assignment
- ran application locally to validate changes
- ran tests to verify they still pass
=> CAMS-215 Corrected multiple assignment bug

backend/functions/case-assignments/case.assignment.function.test.ts, backend/functions/cases/cases.function.test.ts, backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.test.ts, backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.ts, backend/functions/lib/adapters/utils/http-response.test.ts, backend/functions/lib/adapters/utils/http-response.ts, backend/functions/lib/use-cases/attorneys.ts, backend/functions/lib/use-cases/case-management.test.ts, backend/functions/lib/use-cases/case-management.ts, backend/functions/lib/use-cases/case.assignment.ts, user-interface/src/components/CaseAssignment.tsx, user-interface/src/models/api.test.ts, user-interface/src/models/api.ts
Proper error handling, specifically for CosmosDB, but also in general on Case List screen.
Sent back proper error message to front end and handled error display in alert message.
Testing has been updated and coverage increased slightly.
=> CAMS-216 handle cosmos errors

user-interface/src/components/CaseDetail.tsx
Add ARIA label for region id on case details screen
=> CAMS-209 Added aria label for region id

.pre-commit-config.yaml, architecture/export-architecture-diagrams.sh, ops/helper-scripts/accessibility-test.sh, ops/helper-scripts/az-app-deploy.sh, ops/helper-scripts/az-delete-branch-resources.sh, ops/helper-scripts/az-func-deploy.sh, ops/helper-scripts/azure-deploy-rg.sh, ops/helper-scripts/azure-deploy.sh, ops/helper-scripts/data/import-data.sh, ops/helper-scripts/dev-add-allowed-ip.sh, ops/helper-scripts/dev-rm-allowed-ip.sh, ops/helper-scripts/generate-stackname.sh, ops/helper-scripts/pre-commit-hook-content, ops/helper-scripts/sec-update-baseline.sh, ops/helper-scripts/set-up-git-hooks.sh
Improve code quality by including bash script linter and update scripts to mitigate lint issues.
- Include shellcheck as part of pre-commit process
- Resolve all lint issues in existing bash scripts
- Execute branch deployment to verify all deployment related scripts
- Run locally any adhoc helper/utility scripts
=> CAMS-162 Updated shell scripts base on shellcheck linter

user-interface/src/case-detail/CaseDetailScreen.scss, user-interface/src/case-detail/CaseDetailScreen.test.tsx, user-interface/src/case-detail/panels/CaseDetailBasicInfo.tsx
Corrected display message when Tax ID Information is not available
- changed message for unavailable TaxId information for debtor
- changed spaced for ul items to display address
ran locally and verified changes
=> CAMS-242 Fixed tax info message and ul spacing

user-interface/src/case-detail/panels/CaseDetailCourtDocket.scss, user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx
Sort docket entries by sequence number as a stand in for date.
Added sort toggle button to the user case docket screen.
Sorted docket by the toggled sort direction.
Added unit tests to confirm the sorting worked as expected.
=> CAMS-222 Sort docket entries

backend/functions/lib/adapters/gateways/dxtr/case-docket.mock.gateway.ts, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/adapters/types/cases.d.ts, backend/functions/lib/testing/mock-data/debtor-attorneys.mock.ts, dev-tools/test-data/scripts/caseAttorneys.ts, user-interface/src/case-detail/CaseDetailScreen.scss, user-interface/src/case-detail/panels/CaseDetailBasicInfo.test.tsx, user-interface/src/case-detail/panels/CaseDetailBasicInfo.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.scss, user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx, user-interface/src/lib/type-declarations/chapter-15.d.ts
Show debtor attorney's office on case detail
* Amended SQL to return the AT_OFFICE value
* Added office to debtor attorney model returned from API
* Added debtor attorney office to case detail in UI
=> CAMS-247 Add debtor attorney office to case detail

user-interface/.pa11yci, user-interface/package-lock.json, user-interface/package.json, user-interface/src/App.test.tsx, user-interface/src/case-detail/CaseDetailScreen.scss, user-interface/src/case-detail/CaseDetailScreen.test.tsx, user-interface/src/case-detail/CaseDetailScreen.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx, user-interface/src/case-detail/panels/CaseDetailHeader.test.tsx, user-interface/src/case-detail/panels/CaseDetailHeader.tsx, user-interface/src/case-detail/panels/CaseDetailNavigation.d.ts, user-interface/src/case-detail/panels/CaseDetailNavigation.scss, user-interface/src/case-detail/panels/CaseDetailNavigation.test.tsx, user-interface/src/case-detail/panels/CaseDetailNavigation.tsx, user-interface/src/case-detail/panels/CaseDetailScrollPanelRef.d.ts, user-interface/src/lib/components/MultiSelect.scss, user-interface/src/lib/components/MultiSelect.tsx, user-interface/src/lib/type-declarations/chapter-15.d.ts
Add mechanism for filtering list of dockets by summary text.
- Added MultiSelect component used to filter docket list
- Include new react-select dependency
- Override default react-select component style
- Moved sort, search and filter ui components to the left sidebar
- Updated pa11y test and include automated unit tests
- Maintain unit test coverage above 90%
- pa11y test pass
- Manual inspection of web application
=> CAMS-223 filter docket

common/src/feature-flags.ts, user-interface/src/case-detail/CaseDetailScreen.test.tsx, user-interface/src/case-detail/CaseDetailScreen.tsx, user-interface/src/case-detail/CaseDetailScreenSortAndFilter.test.tsx, user-interface/src/lib/hooks/UseFeatureFlags.ts
Jira ticket: CAMS-258
Remove any dependence on docket-search-enabled flag.
Removed use of docket-search-enabled flag.
verified that code still works as expected and that all tests pass.
All tests are passing.
=> CAMS-258 Removed docket-search-enabled from all code

backend/functions/lib/adapters/controllers/cases.controller.test.ts, backend/functions/lib/adapters/gateways/dxtr/case-docket.dxtr.gateway.ts, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/adapters/utils/date-helper.test.ts, backend/functions/lib/adapters/utils/date-helper.ts, user-interface/src/case-assignment/CaseAssignmentScreen.tsx, user-interface/src/case-detail/CaseDetailScreen.test.tsx, user-interface/src/case-detail/panels/CaseDetailBasicInfo.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx, user-interface/src/lib/models/chapter15-mock.api.cases.ts, user-interface/src/lib/utils/datetime.test.ts, user-interface/src/lib/utils/datetime.ts
Change the format of dates in the UI
* Changed the format functions in the SQL statements to return ISO dates.
* Add a date format utility in the UI.
* Use the utility function to reformat dates in the UI components.
* Wrote unit tests to confirm the format utility function works as expected.
=> CAMS-252 reformat dates

user-interface/.pa11yci, user-interface/src/case-detail/CaseDetailScreen.tsx, user-interface/src/case-detail/CaseDetailScreenSortAndFilter.test.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx, user-interface/src/case-detail/panels/CaseDetailNavigation.tsx, user-interface/src/lib/components/uswds/DateRangePicker.test.tsx, user-interface/src/lib/components/uswds/DateRangePicker.tsx
Filter docket by date range
* Implemented DateRangePicker component
* Integrated DateRangePicker component into CaseDetailScreen
Added unit tests to increase coverage for CaseDetailScreen and CaseDetailCourtDocket components.
Removed pa11y test for case docket screen due to headless browser not supporting the latest Javascript language features, specifically Array.prototype.findLast.
=> CAMS-254 filter by date range

user-interface/package-lock.json
Moderate risk packages flagged by Github Dependabot updated.
- Moderate risk packages mitigated with `npm audit fix`
- Verify build and test passes check
=> CAMS-254 Update npm packages flagged for moderate risk

user-interface/src/case-assignment/AssignAttorneyModal.tsx, user-interface/src/case-assignment/CaseAssignmentScreen.tsx
Jira ticket: CAMS-90
Update alert message after editing assignments to properly identify who was added and who was unassigned from the case.
No changes made to testing.  The particular update function is not currently being tested due to the difficulty in testing it.  We plan to revisit at a later date to add to testing.
=> CAMS-90 modify success alert

user-interface/src/App.tsx, user-interface/src/configuration/featureFlagConfiguration.ts, user-interface/src/lib/hooks/UseFeatureFlags.test.ts, user-interface/src/lib/hooks/UseFeatureFlags.ts
Add test coverage
Added test coverage for useFeatureFlag hook.
It is a test.
=> CAMS-249 Add test coverage for useFeatureFlag hook

.github/workflows/continuous-deployment.yml
Jira ticket: CAMS-293
Now that Veracode outage is resolved, we need to re-enable this pipeline-level SAST scan.
Uncommented out some code
Will re-run the job
There may be some fixes that we have to implement on other branches once this is merged in.
=> uncomment veracode pipeline scan

docs/troubleshooting.md, user-interface/src/case-assignment/CaseAssignmentScreen.tsx, user-interface/src/review-orders/ReviewOrdersScreen.scss, user-interface/src/review-orders/ReviewOrdersScreen.tsx
Massage the Orders Accordion content to look more presentable.
USWDS classes added to screen elements as well as HTML to alter the grid layouts.
No functional code altered, so no tests needed.
=> CAMS-264 UI updates

backend/functions/orders-manual-sync/function.json, backend/functions/orders-manual-sync/orders-sync.function.ts
Add an endpoint to trigger order sync
Added function to call same logic as the order sync timerFunction.
Manual testing
=> CAMS-263 Added http trigger for orders-manual-sync

backend/functions/lib/controllers/orders/orders.controller.test.ts, backend/functions/lib/controllers/orders/orders.controller.ts, backend/functions/lib/use-cases/orders/orders.ts, backend/functions/orders-manual-sync/function.json, backend/functions/orders-manual-sync/orders-manual-sync.function.test.ts, backend/functions/orders-manual-sync/orders-manual-sync.function.ts, backend/functions/orders-sync/orders-sync.function.test.ts
Add extra logging to sync endpoint for debugging
Testing coverage is above 90%.
Did manual testing to ensure that logging is working.
=> CAMS-263 enhance trigger

backend/functions/lib/adapters/gateways/dxtr/mock.orders.gateway.ts, backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.test.ts, backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.ts, backend/functions/lib/adapters/gateways/runtime-state.cosmosdb.repository.test.ts, backend/functions/lib/controllers/orders/orders.controller.test.ts, backend/functions/lib/testing/mock.cosmos-client-humble.ts, backend/functions/lib/use-cases/gateways.types.ts, backend/functions/lib/use-cases/orders/orders.model.ts, backend/functions/lib/use-cases/orders/orders.test.ts, backend/functions/lib/use-cases/orders/orders.ts, backend/functions/orders-manual-sync/orders-manual-sync.function.test.ts, backend/functions/orders-manual-sync/orders-manual-sync.function.ts, backend/functions/orders-sync/orders-sync.function.test.ts, common/src/feature-flags.ts, docs/running.md, user-interface/src/review-orders/TransferOrderAccordion.tsx, user-interface/vite.config.mts
Fix query bug stopping order sync
* Updated query to properly expand the list of regions and chapters.
* Misc other code coverage and grooming.
* Unit tests all above threshold.
* Manual testing and observation of fixes to order sync.
=> CAMS-263 Fix query bug stopping order sync

user-interface/src/lib/components/SearchableSelect.test.tsx, user-interface/src/lib/components/SearchableSelect.tsx, user-interface/src/lib/components/uswds/Input.test.tsx, user-interface/src/lib/components/uswds/Input.tsx
Increased front-end coverage
Added coverage for SearchableSelect setValue, resetValue, and clearValue.
Added full coverage for Input component.
Added coverage for SearchableSelect setValue, resetValue, and clearValue.
Added full coverage for Input component.
=> CAMS-263: Added coverage

user-interface/src/review-orders/TransferOrderAccordion.tsx
Improve accessibility of the review orders screen.
Added ARIA labels as necessary.
* Manually tested with MacOS voice over.
=> CAMS-263 Improve a11y for review orders accordion

user-interface/src/case-detail/panels/CaseDetailBasicInfo.test.tsx, user-interface/src/case-detail/panels/CaseDetailBasicInfo.tsx, user-interface/src/lib/models/chapter15-mock.api.cases.ts, user-interface/src/lib/type-declarations/chapter-15.d.ts
Fix minor issues from PR
Manually tested fixes are in place.
=> CAMS-266 Minor fixes from PR

user-interface/src/data-verification/DataVerificationScreen.scss, user-interface/src/data-verification/DataVerificationScreen.tsx
Jira ticket: CAMS-318
- Add headers to the Data Verification screen 
- Addition column headers to the table within the data verification screen
- ran the app locally and verified the headers appear correctly
=> Added headers to Data Verification screen

user-interface/src/data-verification/DataVerificationScreen.scss, user-interface/src/data-verification/DataVerificationScreen.test.tsx, user-interface/src/data-verification/DataVerificationScreen.tsx, user-interface/src/data-verification/TransferOrderAccordion.tsx
Fix some UX issues.
- Replace `Case ID` with `Case Number`
- Prevent display of accordions during loading
Sufficient tests already exist.
=> CAMS-318: dod

backend/functions/attorneys/attorneys.function.ts, backend/functions/case-assignments/case.assignment.function.ts, backend/functions/cases/cases.function.ts, backend/functions/healthcheck/healthcheck.db.cosmos.ts, backend/functions/healthcheck/healthcheck.db.sql.ts, backend/functions/healthcheck/healthcheck.function.ts, backend/functions/healthcheck/healthcheck.info.ts, backend/functions/lib/adapters/controllers/attorneys.controller.ts, backend/functions/lib/adapters/controllers/case.assignment.controller.ts, backend/functions/lib/adapters/controllers/cases.controller.test.ts, backend/functions/lib/adapters/controllers/cases.controller.ts, backend/functions/lib/adapters/gateways/attorneys.inmemory.gateway.ts, backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.ts, backend/functions/lib/adapters/gateways/cases.cosmosdb.repository.ts, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.ts, backend/functions/lib/adapters/gateways/inmemory.database.gateway.ts, backend/functions/lib/adapters/gateways/mock.cases.gateway.ts, backend/functions/lib/adapters/gateways/orders.cosmosdb.repository.ts, backend/functions/lib/adapters/gateways/runtime-state.cosmosdb.repository.ts, backend/functions/lib/adapters/services/logger.service.test.ts, backend/functions/lib/adapters/services/logger.service.ts, backend/functions/lib/adapters/utils/application-context-creator.test.ts, backend/functions/lib/adapters/utils/application-context-creator.ts, backend/functions/lib/adapters/utils/database.ts, backend/functions/lib/use-cases/attorneys.ts, backend/functions/lib/use-cases/case.assignment.ts, backend/functions/orders-manual-sync/orders-manual-sync.function.test.ts, backend/functions/orders-sync/orders-sync.function.test.ts
Consolidate logging functionality
Logging functionality consolidated and saved in the services/logger.services.ts file.
Code and tests refactored to properly use LoggerImpl object.
All tests have been updated and are passing.
LoggerImpl has 100% coverage across the board.
=> VER-34 verify log output

user-interface/src/case-assignment/CaseAssignmentScreen.tsx
Veracode flagged potential CWE-117 issues with frontend logic that needs to be reviewed and mitigated. 
- Determine Veracode findings correspond to logging needed only for development. Lines with the log entries has been removed. 
- Passing CI pipeline run
This pull request will mitigate both VER-32 and VER-33
=> VER-32 Mitigate finding related to frontend logging

user-interface/.pa11yci, user-interface/src/data-verification/DataVerificationScreen.scss, user-interface/src/data-verification/DataVerificationScreen.test.tsx, user-interface/src/data-verification/DataVerificationScreen.tsx, user-interface/src/data-verification/TransferOrderAccordion.scss
The purpose of these changes are to refine the UI components of the Data Verification Screen Order Status Filters
- css styling changes for the filter buttons
- addition of the Filters on the data verification screen
- Ran Locally and tested the application
Will likely need to revisit styling pending user feedback
=> Cams 268 filter orders UI

architecture/cams.dsl, docs/architecture/diagrams/cams-containers.md, docs/architecture/diagrams/cams-context.md, docs/architecture/diagrams/cams-functions-api-components.md, docs/architecture/diagrams/cams-webapp-components.md, docs/architecture/diagrams/cams-webapp-with-functions-api.md
Our architecture documentation is missing some of the more recent Azure Functions and the Data Verification screen.
- Update cams.dsl to reflect the current state of the system
- Update diagram markdown files
=> Update architecture documentation

user-interface/src/data-verification/TransferOrderAccordion.test.tsx, user-interface/src/data-verification/TransferOrderAccordion.tsx
Jira ticket: CAMS-325
Add Parentheses to court div in the new case transfer screen to keep the format consistent
- added parentheses 
- updated tests
- Ran locally and verified the tests work and the app functions as expected
=> Updated formatting for new case transfer court division and corresponding tests

.gitignore, user-interface/src/data-verification/CaseTable.tsx
Jira ticket: CAMS-331
Added court division name in parens to the caseTable component to be displayed next to the court name.
Testing unneccesary.
=> CAMS-331: Added court division in () to caseTable component

ops/scripts/utility/update-dependencies.sh
Make dependency updates easier.
Adds a script which can be run from the repository root to set up a branch for performing dependency updates and run `npm update --save` on all projects in the repo.
Ran the script locally.
Will not handle running `npm audit` or `npm outdated` since these scripts are more interactive. Future improvements might run these commands and output to a file or run them and just keep track of state so that the developer can be notified of the need to address vulnerabilities or evaluate major version upgrades.
=> Add a script to aid in dependency updates

.github/workflows/azure-remove-branch.yml
Automate clean up of Azure resources in Flexion environment from a branch deployment 
- Initial GHA workflow template to begin development
=> CAMS-122 Initial GHA workflow for automating Azure resource clean up

.github/workflows/azure-remove-branch.yml, .github/workflows/continuous-deployment.yml, ops/cloud-deployment/lib/subscription/resource-group-deploy.bicep, ops/cloud-deployment/lib/subscription/ustp-cams-rg.bicep, ops/scripts/pipeline/azure-deploy-rg.sh
Automate the clean up of Azure resources in the Flexion environment
- Create new GHA workflow to execute clean up script
- Update deployment scripts to include tags on Azure resource group used for application resources. Information included is branch name and hash id used to create resource groups.
- Add event trigger for new GHA clean up workflow on pull request close activities
- Verify Azure resource tagging with expected values
- Verify new GHA workflow remove Azure resources by id
This workflow is only applicable to Flexion environment to clean up development branches that was deployed into Azure.
=> CAMS-122 Automate clean up of Azure resources

.github/workflows/azure-remove-branch.yml
GHA clean up job fails to find target resources. Check job is expecting the short hash that was passed in.
- Update logic to generate a short hash value
Will be validated once merged to main
=> CAMS-122 Update to generate short hash id

user-interface/src/case-assignment/CaseAssignmentScreen.tsx, user-interface/src/case-detail/CaseDetailScreen.tsx, user-interface/src/data-verification/ConsolidationOrderAccordion.tsx, user-interface/src/data-verification/DataVerificationScreen.tsx, user-interface/src/data-verification/TransferOrderAccordion.tsx, user-interface/src/lib/hooks/UseApi.test.ts, user-interface/src/lib/hooks/UseApi.ts
Replace the boilerplate code scattered through the UI to select the API or mock API with a React hook.
Added a React hook to return the appropriate API implementation. Integrated the change into React function components using the API.
Tests written.
=> CAMS-335 Add useApi hook

backend/functions/lib/controllers/orders/orders.controller.ts, backend/functions/lib/use-cases/orders/orders.ts, common/src/cams/orders.ts, common/src/cams/test-utilities/mock-data.ts, user-interface/src/data-verification/ConsolidationOrderAccordion.test.tsx, user-interface/src/data-verification/ConsolidationOrderAccordion.tsx, user-interface/src/data-verification/ConsolidationOrderModal.scss, user-interface/src/data-verification/ConsolidationOrderModal.test.tsx, user-interface/src/data-verification/ConsolidationOrderModal.tsx, user-interface/src/lib/components/uswds/Radio.test.tsx, user-interface/src/lib/components/uswds/Radio.tsx, user-interface/src/lib/type-declarations/input-fields.d.ts
Added Consolidation Type to Consolidation Modal, API, and Cosmos
Over 90% test coverage
=> CAMS-272 consolidation type

test/e2e/playwright.config.ts, test/e2e/playwright/consolidation-orders.spec.ts
Temporary improvement to get end-to-end Playwright job passing
- Update Playwright config
- Will verify in main
=> CAMS-272 e2e testing

.github/workflows/continuous-deployment.yml, .github/workflows/playwright-e2e.yml, test/e2e/playwright.config.ts, test/e2e/playwright/consolidation-orders.spec.ts
Seeing inconsistent results with e2e Playwright testing when executed locally and in CICD pipeline
- Minor refactoring of consolidation tests
- Enable trace recording for all tests
- Add step to CICD workflow to upload Playwright test report
- Verified with local execution
- Verified in CICD pipeline with branch deployment
- Investigation on this issues shows that there is some differences when running integration test with the browsers compared to headless mode.
=> CAMS-272 Update to e2e testing Playwright configuration

test/e2e/playwright/consolidation-orders.spec.ts
Fix broken E2E test.
Ran the E2E test locally to confirm.
=> CAMS-366 - Fix e2e test

user-interface/src/data-verification/ConsolidationOrderAccordion.test.tsx, user-interface/src/data-verification/ConsolidationOrderAccordion.tsx
Increase coverage for case consolidation UI
Added additional unit tests
Test coverage above threshold.
=> CAMS-301 - Add reject consolidation tests

user-interface/src/data-verification/ConsolidationCasesTable.tsx, user-interface/src/data-verification/TransferOrderAccordion.tsx
Fix docket wrapping issue with consolidation
Added a USWDS token to the docket entry paragraph.
Manually tested.
=> CAMS-369 Fix docket wrapping issue with consolidation

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-database-deploy.yml, .github/workflows/sub-deploy.yml, docs/operations/scripts.md, ops/scripts/pipeline/az-cosmos-deploy.sh
Jira ticket: CAMS-237
Only deploy e2e database if e2e tests will be run on slots
Logic to only deploy e2e databases if slots are being deployed
Deployed to environment without slot, deployed to environment with slots
This is something I noticed during pipeline runs and felt it was not expected functionality.
=> CAMS-237 e2e update

user-interface/src/data-verification/ConsolidationOrderAccordion.tsx
Remove help text from consolidation accordion
Remove help text from consolidation accordion
Manual testing.
=> CAMS-341 - Remove help text from consolidation accordion

ops/git-setup/commit.template
=> Update commit template

user-interface/src/lib/components/CaseNumberInput.tsx, user-interface/src/lib/components/uswds/Input.test.tsx, user-interface/src/lib/components/uswds/Input.tsx, user-interface/src/lib/components/uswds/forms.scss, user-interface/src/search/SearchScreen.tsx
Fine tuning based on UX review.
- Added an clear button capability to the base <Input> component
- Fixed the state of messages on the search screens
- Miscellaneous label and header level changes
- Use case title instead of debtor name in results table
Test coverage is above threshold.
=> CAMS-383 DOD

.github/workflows/reusable-database-deploy.yml, ops/cloud-deployment/ustp-cams-cosmos.bicep
Jira ticket: CAMS-315
fixed network operator so networks properly deploy on Flexion side 
added ternary to cosmos bicep file 
deployed to Flexion side on a development environment
=> CAMS-315: Flexion deployment fix

docs/contributing/_sidebar.md, docs/contributing/package-updates.md
- Document the auto-update
- Document the procedure for generating and using gpg keys for signing automated commits
=> Add documentation of auto-update functionality

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-build-info.yml
Allow full deployment on main branch
Describe what has changedUpdates to workflow to allow full deployment (non-slot) on main
=> CAMS-382 Updated workflow to allow full deployment on main

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-build-info.yml
PR Merges were only running a full deployment, this fixes that. 
When workflow_dspatch parameters are not passed in they are null values. This was causing an issue with the enableSlotDeployment parameter evaluation for deploying slots and performing e2e testing. fixed the evaluation logic
ran in testing branch, validated logic
=> Slot Deployment fix

.github/workflows/reusable-build-info.yml
continuous deployment was attempting to deploy vnet everytime, fixed that check
correct eval on vnet deployment
built and ran test
=> corrected vnet deploy issue

user-interface/src/data-verification/DataVerificationScreen.scss, user-interface/src/data-verification/DataVerificationScreen.tsx
Make Filter buttons within the data verification screen more usable and understandable
- Container added for the Event Status and Event Type
- Added styles based on the enabled/disabled properties of filters
Ran the application locally and validated the filter were functioning properly
=> Cams 391 filter usability

.github/workflows/sub-deploy-code-slot.yml
E2E tests are failing within the pipeline but passing locally, want to get to the root of this problem, we are continuing on fail of D2E until we do
Add condition allowing slow swap despite e2e failure
deployed environment directly and with slot deployment
=> Continue after e2e fail

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-database-deploy.yml, .github/workflows/sub-deploy-code-slot.yml
This is a test PR with a small change
=> testing branch cleanup -- prior to main

.github/PULL_REQUEST_TEMPLATE.md, backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/controllers/cases/cases.controller.ts, common/src/api/search.ts, user-interface/src/lib/components/CamsSelectMulti.tsx, user-interface/src/lib/components/CaseNumberInput.tsx, user-interface/src/lib/hooks/UseApi2.ts, user-interface/src/search/SearchResults.test.tsx, user-interface/src/search/SearchResults.tsx, user-interface/src/search/SearchScreen.test.tsx, user-interface/src/search/SearchScreen.tsx
Enable users to search for cases by chapter number
* Added chapter number to filters form
* Added chapter number filter capability to API
Test coverage above 90%.
=> CAMS-375 search by chapter

user-interface/src/lib/components/uswds/PaginationButton.scss
Hovering over pagination on search screen causing cursor to change to input
Added style that change the cursor to a pointer
ran app locally and test cursor hover
=> CAMS-398 pagination hover state fix

user-interface/src/case-assignment/CaseAssignmentScreen.tsx, user-interface/src/case-detail/panels/CaseDetailBasicInfo.test.tsx, user-interface/src/case-detail/panels/CaseDetailBasicInfo.tsx
Ensure that staff assignments may only be added or modified on a chapter 15 case.
`/case-assignments` page only lists chapter 15 cases. 
On case details screen, basic info panel, on a chapter 15 case will allow user to edit assignments.  Edit button is only displayed for chapter 15 case.
Basic Case Info screen test updated to make sure that the case in test is a chapter 15 case.
=> CAMS-403 limit assignments to chapter 15

.github/workflows/azure-remove-branch.yml, .github/workflows/reusable-database-deploy.yml, ops/scripts/pipeline/az-cosmos-deploy.sh
Remove Branch Resources workflow was not removing the database properly. I updated the workflow to have the proper name when deleting the database
- update name generation for database deletion.
- added logic to only deploy e2e db if it doesn't already exist
- ran script locally
=> fixed remove-branch workflow to properly remove db

ops/scripts/pipeline/az-app-deploy.sh, ops/scripts/pipeline/slots/az-app-slot-deploy.sh
Azure seemed to have updated src config deployment and the tracking caused timeout on the frontend deployment
The src config zip deployment tracked the status of deployment, and an update azure seems to have made cause 
Deployed environment on 401 branch to validate non-timeout deployment
=> changed deployment command of frontend to avoid new azure issue

user-interface/src/data-verification/ConsolidationOrderAccordion.tsx, user-interface/src/data-verification/DataVerificationScreen.scss, user-interface/src/data-verification/TransferOrderAccordion.tsx
Fix aligntment issues of Event Status & Type on Data Verification Screen
- addition of classes to Event Status and Event Type
- fixed styling to align the properly
Ran locally and verified elements are aligned
=> Cams 408 event tag alignment

backend/functions/lib/configs/authorization-configuration.ts
missing url for prd ustp as a mock issuer for auth
add prd url to mockIssuers
n/a
=> added prd url to mockissuers to fix PRD environment

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-build-info.yml, .github/workflows/reusable-deploy.yml, .github/workflows/sub-build.yml, .github/workflows/sub-deploy-code-slot.yml, .github/workflows/sub-deploy-code.yml, .github/workflows/sub-deploy.yml, backend/functions/lib/adapters/gateways/okta/okta-gateway.test.ts, backend/functions/lib/adapters/gateways/user-session.gateway.test.ts, backend/functions/lib/adapters/gateways/user-session.gateway.ts, backend/functions/lib/adapters/types/authorization.ts, backend/functions/lib/adapters/utils/application-context-creator.ts, backend/functions/lib/configs/application-configuration.ts, backend/functions/lib/configs/authorization-configuration.test.ts, backend/functions/lib/configs/authorization-configuration.ts, backend/functions/lib/factory.ts, backend/functions/lib/testing/mock-gateways/mock-oauth2-gateway.ts, backend/functions/package.json, common/src/cams/login.ts, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/main.bicep, ops/scripts/pipeline/set-login-provider-config.sh, test/e2e/playwright/auth-setup.ts, user-interface/public/nginx.conf, user-interface/src/login/providers/mock/MockLogin.test.tsx, user-interface/src/login/providers/mock/MockLogin.tsx, user-interface/src/login/providers/okta/OktaProvider.test.tsx, user-interface/src/login/providers/okta/OktaProvider.tsx
Jira ticket: CAMS-401
We have Okta for USTP now, so we do not need mockIssuer URLS for those 2 environments any more
removal of USTP Urls
N/A
=> CAMS-401 remove USTP urls from mock issuer

backend/functions/lib/configs/authorization-configuration.ts
Jira ticket: CAMS-401
,
USTP side OKTa Url did not match out accepted domain conventions
we added the correct URL to the auth-config
=> CAMS-401 added ustp test env okta tenant

ops/cloud-deployment/backend-api-deploy.bicep
Jira ticket: CAMS-401
Environment Variables in api were not matching what was being set in the code
fix naming of env vars in bicep template
N/A
=> CAMS-401 corrected the name of the Azure env vars on the backend

backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/functions/lib/adapters/gateways/dxtr/offices.gateway.ts, backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.ts, dev-tools/test-data/misc/csv/AO_OFFICE.csv
Update the source of the Division Name to the newly create AO_OFFICE.OFFICE_NAME_DISPLAY for user friendly names
- Creation of new OFFICE_NAME_DISPLAY column in AO_OFFICE table  and copied data from OFFICE_NAME in
- Update SQL queries to correctly pull from new column
- update existing CSV of AO_OFFICE with values
- Ran the app locally and went through tests
- ran local e2e
n/a
=> CAMS-392 division name source

backend/functions/lib/configs/authorization-configuration.test.ts, backend/functions/lib/configs/authorization-configuration.ts, common/src/cams/utilities.test.ts, common/src/cams/utilities.ts, user-interface/src/login/login-library.test.ts, user-interface/src/login/login-library.ts
Plan B to replace JSON environment variables
Added a library to turn a pipe-delimited string if key-value pairs into a Record or Map.
100% unit test coverage
=> CAMS-401 Added key value utilities to common

backend/functions/lib/configs/authorization-configuration.test.ts, backend/functions/lib/configs/authorization-configuration.ts
Jira ticket: CAMS-401
Remove inferring the provider from the issuer since provider is available as an env var.
* Read provider from env var.
* Remove inference function.
Module fully covered.
=> CAMS-401 Remove provider inference from issuer logic

user-interface/src/data-verification/transfer/PendingTransferOrder.test.tsx, user-interface/src/data-verification/transfer/SuggestedTransferCases.test.tsx, user-interface/src/data-verification/transfer/SuggestedTransferCases.tsx, user-interface/src/lib/components/Pill.scss, user-interface/src/lib/components/combobox/ComboBox.scss, user-interface/src/lib/components/combobox/ComboBox.test.tsx, user-interface/src/lib/components/combobox/ComboBox.tsx
Replace all usage of CamsSelectSingle with new Combobox.
(the one exception is the cases consolidation screen)
screens, components, and tests updated to use Combobox rather than CamsSelectSingle.  Consolidation Accordion however was not touched and CamsSelectSingle still exists in the lib/components folder for now.
Test coverage is above 90%.
The cases consolidation accordion will be updated at a later date and CamsSelectSingle can be removed at that time, along with associated tests.
=> CAMS-412 replace all single selects with combobox

test/e2e/playwright/transfer-orders.spec.ts
Jira ticket: CAMS-412
Update E2E tests with corresponding new combo box inputs for court selections
update new court select in e2e tests
updated tests and ran locally
=> CAMS-412 Updated e2e tests to include new combobox

.github/workflows/continuous-deployment.yml, .github/workflows/e2e-test.yml, .github/workflows/reusable-backend-slot.yml, .github/workflows/reusable-build-info.yml, .github/workflows/reusable-deploy.yml, .github/workflows/reusable-e2e.yml, .github/workflows/reusable-frontend-slot.yml, .github/workflows/sub-deploy-code-slot.yml, .github/workflows/sub-deploy-slot-resources.yml, .github/workflows/sub-deploy.yml, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/main.bicep, ops/scripts/pipeline/azure-deploy.sh
further simplify the template
Simplified logic even further
=> CAMS-394 slot config update

.github/workflows/reusable-e2e.yml
Update e2e to use proper env var for CAMS_LOGIN_PROVIDER
=> CAMS-406 changed provider for e2e tests

test/e2e/playwright.config.ts, test/e2e/playwright/auth-setup.ts, test/e2e/playwright/transfer-orders.spec.ts
Jira ticket: CAMS-406
Fix e2e tests for role authorization
Small changes in e2e tests
Updated and ran e2e against host application
=> CAMS-406 Update role for mock login in e2e test

backend/functions/case-history/case-history.function.test.ts, backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.test.ts, backend/functions/lib/controllers/case-history/case-history.controller.test.ts, backend/functions/lib/controllers/case-history/case-history.controller.ts, backend/functions/lib/cosmos-humble-objects/fake.assignments.cosmos-client-humble.ts, backend/functions/lib/testing/mock-data/case-history.mock.ts, backend/functions/lib/use-cases/case-assignment.ts, backend/functions/lib/use-cases/case-management.test.ts, common/src/cams/assignments.ts, common/src/cams/history.ts, common/src/cams/test-utilities/mock-data.ts, common/src/cams/test-utilities/mock-user.ts, user-interface/src/case-detail/panels/CaseDetailAuditHistory.test.tsx, user-interface/src/case-detail/panels/CaseDetailAuditHistory.tsx, user-interface/src/lib/hooks/UseApi2.ts, user-interface/src/lib/type-declarations/chapter-15.d.ts
Added the user who made the change to assignments and display on Case History screen.
* Updates to Case History Model and assignments model
* Changed the shape of the data that comes back from API to match our more modern approach.
* Updates to UI to display the name of the user who made the assignment on the Case History screen
* updated front end and backend tests.
Front and Backend test coverage is > 90%
- ~Feature toggles created - Features that are deployed but not released have toggles~
=> CAMS-280 who assigned

user-interface/src/case-detail/CaseDetailScreen.tsx, user-interface/src/search/SearchScreen.tsx
Fix clearing capability on search and docket screen for combo-box
Added onUpdateSelection handler on search screen and Docket screen
Test coverage still above 90%
=> CAMS-419 Fixed Search Screen to reload on clear of combobox

user-interface/src/App.tsx, user-interface/src/lib/components/ScrollToTopButton.tsx, user-interface/src/lib/components/uswds/Icon.tsx, user-interface/src/lib/hooks/UseApi2.ts, user-interface/src/search-results/SearchResults.tsx, user-interface/src/staff-assignment/StaffAssignmentRow.tsx, user-interface/src/staff-assignment/StaffAssignmentScreen.tsx, user-interface/src/staff-assignment/modal/AssignAttorneyModal.tsx
Experiment to fix scrolling button and loading of data in staff assignment screen.
=> CAMS-418 aust my cases  mr madden

user-interface/src/staff-assignment/modal/AssignAttorneyModal.tsx, user-interface/src/staff-assignment/row/StaffAssignmentRow.test.tsx, user-interface/src/staff-assignment/row/StaffAssignmentRow.tsx
Added tooltips and refocus to assignment buttons
* Edit and Assign buttons are now refocused after closing modal
* Edit and Assign buttons have more descriptive tooltips
Tests updated for tooltip changes
- ~Feature toggles created - Features that are deployed but not released have toggles~
=> CAMS-418 assignment button updates

test/e2e/playwright/consolidation-orders.spec.ts, test/e2e/playwright/transfer-orders.spec.ts
use new api response within e2e tests
update e2e tests to use new response coming back from the api
- Ran locally
- deployed environment and ran on hosted**
=> CAMS-356 E2E fix

backend/functions/healthcheck/healthcheck.function.ts, backend/functions/lib/common-errors/bad-request.ts, backend/functions/lib/common-errors/cams-error.ts, backend/functions/lib/common-errors/common-errors.test.ts, backend/functions/lib/common-errors/error-utilities.test.ts, backend/functions/lib/common-errors/forbidden-error.ts, backend/functions/lib/common-errors/not-found-error.ts, backend/functions/lib/common-errors/server-config-error.ts, backend/functions/lib/common-errors/unauthorized-error.ts, backend/functions/lib/common-errors/unknown-error.ts, backend/functions/lib/use-cases/assignment.exception.test.ts, backend/functions/lib/use-cases/assignment.exception.ts, backend/functions/orders-sync/orders-sync.function.ts, common/src/api/http-status-codes.ts
We need to ensure that definition of done has been satisfied before calling the issue done.
Describe what has changed.
=> CAMS-356: DOD

backend/functions/healthcheck/healthcheck.function.ts
=> CAMS-356 Remove stale comment

user-interface/src/data-verification/consolidation/consolidationsUseCase.test.ts, user-interface/src/data-verification/consolidation/consolidationsUseCase.ts
Case number validation was not being called when typing in a case number.
Removed clearing court when modifying case number.
=> CAMS-425: Removed clearing court when modifying case number

test/e2e/playwright/auth-setup.ts, user-interface/src/data-verification/DataVerificationScreen.test.tsx, user-interface/src/data-verification/DataVerificationScreen.tsx
Jira ticket: CAMS-282
Alerts to cover "too many filters" and "no pending orders"
- added "too many filters" and "no pending transfers" for DataVerificationScreen
- updated tests accordingly
- updated role selection within e2e
- ran tests 
- ran locally and verified changed
N/A
=> CAMS-282 Added alerts for Data Verification screen

backend/functions/package-lock.json, backend/functions/package.json
Update only the @azure/functions package.
[Ran full deployment](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/10819542118).
=> Update @azure/functions package

user-interface/src/case-detail/panels/CaseDetailHeader.tsx, user-interface/src/lib/hooks/UseLocationTracker.ts, user-interface/src/login/Login.tsx
Experiment:
When clicking back link, the user is directed back to original tab.  Tab name is updated on login.  If user closes original tab, a new tab is opened with the same name.
Jira ticket: CAMS-428
=> Exp - always take user back to original tab

backend/functions/lib/adapters/gateways/runtime-state.cosmosdb.repository.test.ts
Fix broken test
Tests succeed.
=> CAMS-283 - Fix broken state repo test

user-interface/src/lib/components/Header.scss, user-interface/src/lib/components/Header.test.tsx, user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/cams/MainContent/MainContent.tsx, user-interface/src/lib/utils/caseNumber.test.ts, user-interface/src/login/BlankPage.tsx
Address Header Critical Accessibility issues
This ticket covers accessibility issues that need to be addressed in order to remain compliant with WCAG.
Testing is incomplete at this point.
=> CAMS-426: header critical accessibility issues

backend/functions/lib/adapters/gateways/okta/okta-user-group-gateway.ts, backend/functions/lib/adapters/types/authorization.ts, backend/functions/lib/configs/user-groups-gateway-configuration.ts, ops/cloud-deployment/backend-api-deploy.bicep
Support API key auth for okta admin API
Added a dynamic configuration to okta group sync auth config to use API key or private key authentication.
Manual integration testing
=> CAMS-283 - Support API key auth for okta admin API

backend/functions/lib/adapters/gateways/okta/okta-user-group-gateway.test.ts, backend/functions/lib/adapters/gateways/okta/okta-user-group-gateway.ts, backend/functions/lib/adapters/types/authorization.ts, backend/functions/lib/use-cases/offices/offices.test.ts, backend/functions/lib/use-cases/offices/offices.ts
We want to see useful information in the logs for successful runs of the sync.
- Add logging to the offices use case and okta group api gateway.
- Add query parameter and authorization mode.
Deployed to USTP environment with successful run of the sync function.
=> CAMS-283: logging

user-interface/.pa11yci, user-interface/src/case-detail/CaseDetailScreen.scss, user-interface/src/case-detail/CaseDetailScreen.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.scss, user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx, user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx, user-interface/src/case-detail/panels/CaseDetailHeader.tsx, user-interface/src/case-detail/panels/CaseDetailNavigation.test.tsx, user-interface/src/case-detail/panels/CaseDetailNavigation.tsx, user-interface/src/case-detail/panels/CaseDetailOverview.tsx, user-interface/src/data-verification/consolidation/ConsolidationCasesTable.tsx, user-interface/src/data-verification/transfer/FromCaseSummary.tsx, user-interface/src/lib/components/DocketEntryDocumentList.test.tsx, user-interface/src/lib/components/DocketEntryDocumentList.tsx, user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/combobox/ComboBox.tsx, user-interface/src/lib/components/uswds/DatePicker.tsx, user-interface/src/lib/components/uswds/DateRangePicker.tsx, user-interface/src/lib/components/uswds/modal/Modal.tsx, user-interface/src/staff-assignment/modal/AssignAttorneyModal.tsx
Address Case Details Critical Accessibility Issues
See ticket notes.  All accessibility issues solved with the exception of a few Date Picker issues that can not be resolved using the native date picker.
All tests are passing and cover over 90% of the code.
=> CAMS-441 case detail critical accessibility

ops/cloud-deployment/lib/cosmos/cosmos-containers.bicep, ops/cloud-deployment/params/ustp-cams-cosmos-containers.parameters.json
Jira ticket: CAMS-283
Add TTL to the offices container
- Add ttl to offices container in bicep
deployed environment
- TTL is on did we want to add a formal value?
=> CAMS-283 added ttl policy to cosmos container for offices

docs/running.md
update docs for new changes around CAMS-283
- update running.md to include CAMS_DISABLE_LOCAL_CACHE for frontend and CAMS_USER_GROUP_GATEWAY_CONFIG for backend
N/A
N/A
=> CAMs-283 update running docs to include new vars for 283

user-interface/src/staff-assignment/modal/AssignAttorneyModal.test.tsx, user-interface/src/staff-assignment/modal/AssignAttorneyModal.tsx, user-interface/src/test/bdd-style-unit-tests.md, user-interface/src/test/staff-assignment.test.tsx
Sort attorneys in the case assignment modal.
* added a sort function to the attorney list
* wrote a BDD style test
* manual test
=> CAMS-450 - Sort attorneys

user-interface/src/test/staff-assignment.test.tsx
Ensure the list is not empty and values are strings in the staff assignment unit test.
Added a couple assertions to the test.
Tests pass
=> CAMS-450 Ensure the list is not empty and values are strings

user-interface/.pa11yci, user-interface/src/lib/components/CaseNumberInput.tsx, user-interface/src/lib/components/LoadingSpinner.tsx, user-interface/src/lib/components/Pill.tsx, user-interface/src/lib/components/PillBox.test.tsx, user-interface/src/lib/components/combobox/ComboBox.scss, user-interface/src/lib/components/combobox/ComboBox.test.tsx, user-interface/src/lib/components/combobox/ComboBox.tsx, user-interface/src/lib/components/uswds/Alert.tsx, user-interface/src/lib/components/uswds/Input.tsx, user-interface/src/my-cases/MyCasesScreen.test.tsx, user-interface/src/my-cases/MyCasesScreen.tsx, user-interface/src/search-results/SearchResults.tsx, user-interface/src/search/SearchScreen.scss, user-interface/src/search/SearchScreen.test.tsx, user-interface/src/search/SearchScreen.tsx, user-interface/src/staff-assignment/screen/StaffAssignmentScreen.test.tsx, user-interface/src/staff-assignment/screen/StaffAssignmentScreen.tsx
CAMS-420 case search critical accessibility
Update Case Search screen in accordance with accessibility findings
- added functionality that properly renders and reads alerts in case search in screen reader
- added search button instead of automatically applying searches as it was impacting accessibility
- updated labels and roles of search screen in accordance with accessibility
- for specifics, see google doc for this ticket
- ran application locally with screen reader to verify accessibility updates
- ran pa11y tests locally and in the pipeline to verify accessibility updates
- decided on submit button instead of automatically applying searches
=> CAMS-420 case search critical accessibility 

backend/functions/.gitignore, backend/functions/lib/testing/isolated-integration/export-office-csv.ts, backend/functions/lib/testing/isolated-integration/test-okta-group-api.ts, backend/functions/package.json
Restore okta integration test and add office CSV export
* Restored previously removed okta group API test. Removed console.log
* Added script to export offices in CSV format to temp directory.
Manual testing
=> CAMS-283 restore itest

.github/workflows/continuous-deployment.yml, user-interface/.pa11yci, user-interface/src/data-verification/consolidation/ConsolidationOrderAccordion.test.tsx, user-interface/src/lib/components/combobox/ComboBox.tsx, user-interface/src/lib/testing/testing-utilities.ts, user-interface/src/search/SearchScreen.test.tsx
Describe the reason why this was developed.
Describe what has changed.
=> Cams 432 arthur test

user-interface/src/data-verification/DataVerificationScreen.tsx, user-interface/src/data-verification/TransferOrderAccordion.tsx, user-interface/src/data-verification/transfer/SuggestedTransferCases.test.tsx, user-interface/src/data-verification/transfer/SuggestedTransferCases.tsx, user-interface/src/lib/components/combobox/ComboBox.tsx, user-interface/src/lib/components/uswds/Input.tsx
Jira ticket: CAMS-432
Correct remaining accessibility findings related to CAMS-432 noted in the document
- updated to findings in google doc
- also fixed the issue we were seeing with the new case input on Transfer Order
- ran locally and verified
- deployed environment*
N/A
=> CAMS-432 correct remaining accessibility findings

backend/functions/jest.config.js, backend/functions/lib/testing/analysis/acms-dxtr-divisions/compare-divisions.ts, backend/functions/lib/testing/analysis/export-office-csv.ts, backend/functions/package.json, common/src/cams/courts.ts
Compare ACMS and DXTR divisions
* Added a script to compare and contrast ACMS and DXTR division information.
* This code is not used for production purposes.
Jira ticket: CAMS-454
Manual only. Non production code.
=> CAMS-454 - Compare ACMS and DXTR divisions

backend/functions/lib/adapters/gateways/consolidations.cosmosdb.mongo.repository.ts, backend/functions/lib/adapters/gateways/mongo/mongo-adapter.test.ts, backend/functions/lib/adapters/gateways/mongo/mongo-adapter.ts, backend/functions/lib/adapters/gateways/mongo/mongo-query-renderer.test.ts, backend/functions/lib/adapters/gateways/mongo/mongo-query-renderer.ts, backend/functions/lib/query/query-builder.test.ts, backend/functions/lib/query/query-builder.ts
Good fences rule for mongo sort API
Added orderBy function to QueryBuilder
100% test coverage
=> CAMS-442 add mongo lib sort

CODEOWNERS, ops/cloud-deployment/lib/cosmos/mongo/cosmos-account.bicep
Jira ticket: CAMS-451
Add Azure middleware Ips for portl access to cosmos
Add Azure middleware Ips for portl access to cosmos
deployed
- these will likely need to be continuously updated
=> CAMS-451 removed legacy middlware Ips and added the new ones

user-interface/src/App.scss, user-interface/src/lib/components/Header.scss, user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/uswds/Banner.scss, user-interface/src/lib/components/uswds/Banner.tsx
Jira ticket: CAMS-436
There were originally 3 issues laid out in this ticket.  I quickly ran into a number of other related issues that I felt were important to address.
For instance, it was not possible to scroll left or right on the page at any size.  When the screen gets small enough where a table of data is off the screen, you could not scroll to view it.
Other issues included overlapping text at small screen sizes and focus outline being partially hidden.
This ticket is for addressing accessibility problems with the app header that aren't covered by WCAG requirements.
-  [x] DOJ Logo resizing  _(Not sure what is needed here since logo does not currently resize.)_
-  [x] Move user name and logout button from the banner into the header.
- ~~Ensure the Feedback button is contained …
=> CAMS-436 - Non critical accessibility for the page Header

user-interface/package-lock.json, user-interface/package.json, user-interface/src/lib/components/Header.scss, user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.scss, user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.test.tsx, user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.tsx, user-interface/src/lib/components/combobox/ComboBox.test.tsx
Put logout in a submenu next to page links
Created DropdownMenu component
100% coverage
=> CAMS-436 user menu

.github/workflows/azure-remove-branch.yml, ops/cloud-deployment/lib/cosmos/mongo/cosmos-collections.bicep
Jira ticket: CAMS-442
offices collection previously had combination key of userId and OfficeCode, which was incorrect
switch to id and OfficeCode
deployed
=> CAMS-442 fixed compound index issue on offices

ops/cloud-deployment/lib/cosmos/mongo/cosmos-account.bicep
Jira ticket: CAMS-451
add IP allow connections from government data centers in azure portal
add IP allow connections from government data centers in azure portal
deploy
=> CAMS-451 updated cosmos account bicep with azure portal access

user-interface/src/lib/utils/local-storage.test.ts, user-interface/src/lib/utils/local-storage.ts
Jira ticket: CAMS-477
Implement clear cache on user logout
- added functionality to remove cache storage keys on logout
- ran locally and validated
=> CAMS-477 implemented clear cache storage on logout

.github/workflows/azure-remove-branch.yml, docs/operations/deployment.md, ops/cloud-deployment/lib/cosmos/mongo/cosmos-collections.bicep
TTL not functioning properly in MongoDb. 
Updated the ttl indexing in bicep for the offices collection to allow for ttl to be handled properly within MongoDb
deployed the database with a local script
- additionally fixed the issue with branch resource cleanup
=> CAMS-442 attorney duplicates

user-interface/package-lock.json, user-interface/src/App.scss, user-interface/src/App.test.tsx, user-interface/src/lib/components/Header.scss, user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/ScrollToTopButton.tsx, user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.scss, user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.test.tsx, user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.tsx, user-interface/src/lib/components/cams/linkUtils.test.tsx, user-interface/src/lib/components/cams/linkUtils.ts
Make sure Dropdown menu follows all accessibility rules
Rules followed for Dropdown Menu component:
- https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/
- https://www.w3.org/WAI/ARIA/apg/patterns/menubar/
for more information see https://docs.google.com/document/d/1jWB0gHGiKyAIsX-4o5PQQfbxQgs-bMT_wsGOdyEPA2c/edit?tab=t.0
100% test coverage
=> CAMS-436: Dropdown menu accessibility

user-interface/src/lib/components/Header.scss
Jira ticket: CAMS-436
Right align header menu
n/a
=> CAMS-436 right alignment of header menu

ops/cloud-deployment/main.bicep
Jira ticket: CAMS-461
migration subnet failing due to overlapping IP
Corrected the IP range
deployed
N/A
=> CAMS-461 fixed migration subnet address

.github/workflows/sub-deploy-code-slot.yml, ops/scripts/pipeline/azure-deploy.sh, ops/scripts/pipeline/slots/az-slot-start-stop-operations.sh
Jira ticket: CAMS-461
Migration slot needs to start before swapping or it will fail
- updated script to start migration app
- updated GHA to start
N/A
=> CAMS-461 added start to slot op script and pipeline

.github/workflows/e2e-test.yml, .github/workflows/reusable-e2e.yml
Refine e2e to run quickly and more predictably
remove superfluous steps in e2e
ran deployment and e2e tests
N/A
=> removed superfluous steps from e2e

backend/lib/adapters/gateways/dxtr/orders.dxtr.gateway.ts
We need to sync orders for all regions.
Add all regions to the array to query.
Automated tests still work.
=> CAMS-459: Expand order sync to all regions

.github/workflows/azure-remove-branch.yml
=> test commit

.github/workflows/azure-remove-branch.yml
test new changes to branch deletion workflow and added outputs to help debug
test new changes to branch deletion workflow and added outputs to help debug
N/A
N/A
=> testing new changes

.github/workflows/azure-remove-branch.yml
branch deletion runs were not actively deleting resources 
updated workflow to handle this
- going to run some alidation
=> Branch deletion fix

.github/workflows/azure-remove-branch.yml
properly delete resources on branch deletion
removed logic related to pull request since we only run on deletion
N/A
=> Resource Deletion Fix

.github/workflows/azure-remove-branch.yml
correct branch cleanup workflow so it properly cleans up resources
- corrected erroneous quotes
- cannot test until main
=> corrected branch cleanup workflow

.github/workflows/continuous-deployment.yml, .github/workflows/e2e-test.yml, .github/workflows/reusable-backend-slot.yml, .github/workflows/sub-deploy-code-slot.yml, .github/workflows/sub-deploy-slot-resources.yml, .github/workflows/sub-deploy.yml, test/e2e/playwright/consolidation-orders.spec.ts
Ensure consistency for naming within the workflow, correct errors within e2e workflow, fix if condition on deploy
- Ensure consistency for naming within the workflow
- correct errors within e2e workflow 
- fix if condition on deploy for dependency-updates-auto branch
- removed skips from consolidation
- ran workflow
we will still need to allow a new branch to propagate for dependency-updates-auto
- will update workflow for e2e in the future to provision and destroy an e2e database for main during each run to ensure consistent data
=> corrected naming, e2e workflow, and dependency if condition

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-build-frontend.yml, .github/workflows/sub-build.yml, .github/workflows/sub-deploy-code-slot.yml, .github/workflows/sub-deploy.yml, ops/scripts/pipeline/endpoint-test.sh
Made frontend build a reusable workflow so we can properly handle setting the app insights connection string during build time
- created reusable build template for frontend 
- constructed query to be able to get string for newly created appi resource
- properly set env for APP_INSIGHT_CONNECTION_STRING prior to deployment
- Running deployment Workflow
=> Proper handling of Frontend artifact with Appi connection string

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-build-frontend.yml, .github/workflows/reusable-deploy.yml, .github/workflows/reusable-e2e.yml, .github/workflows/reusable-endpoint-test.yml, .github/workflows/sub-build.yml, .github/workflows/sub-deploy.yml, docs/operations/deployment.md, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/frontend-webapp-deploy.bicep, ops/cloud-deployment/lib/app-insights/webapp-insights.bicep, ops/cloud-deployment/lib/network/ustp-cams-network.bicep, ops/cloud-deployment/main.bicep, ops/scripts/pipeline/azure-deploy.sh, ops/scripts/pipeline/endpoint-test.sh
- modularize app insights and alert components for webapp
- clean up some github vars
- prevent alerts from deploying on dev branches
- modularized frontend build so we can build downstream after infra has been deployedwith proper app insights connection
- cleanup some static components with .net suffix
- modularized app insights and alert components in the bicep
- removed AZ_HOST_SUFFIX
- corrected dns zone suffix
- modification to workflow to build frontend a second time once the infrastructure has been deployed
- Tested deployment several times on different branches
host_suffix was not removed from shell script yet to prevent USTP from failing
=> CAMS-417 App Insights Bicep

common/eslint.config.mjs, user-interface/eslint.config.mjs, user-interface/package-lock.json, user-interface/package.json, user-interface/src/lib/components/uswds/Banner.test.tsx
Updated ESLint with react-plugin & hooks
- added react plugin to eslint
- ran eslint locally and within pipeline
N/A
=> CAMS-393 add react plugin

backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts, backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, backend/lib/adapters/types/cases.d.ts, common/src/cams/cases.ts, user-interface/src/case-detail/panels/CaseDetailOverview.test.tsx, user-interface/src/case-detail/panels/CaseDetailOverview.tsx
Display information on Case Details screen about Ambiguous Transfers
* Modified Cases Dxtr gateway to return transfer date.
* Mofified Case Detail screen to display ambiguous transfer information
Added tests to backend and frontend
=> CAMS-491 - Ambiguous transfer indication

backend/lib/adapters/gateways/okta/HumbleVerifier.ts, backend/lib/adapters/gateways/okta/okta-gateway.ts, backend/lib/use-cases/user-session/user-session.ts, common/src/cams/jwt.test.ts, common/src/cams/jwt.ts
Jira ticket: CAMS-497
Retry JWT verification when a ECONNRESET error is encountered.
Added retry logic around JWT verification code
=> CAMS-497 - Retry JWT verification when ECONNRESET encountered

ops/cloud-deployment/lib/cosmos/mongo/cosmos-collections.bicep
We need the user session cache to remove old sessions automatically.
Configure an index for the collection.
- Added documents prior to configuring the index to see if they are deleted.
- This is validated to work.
- Added documents after configuring the index to verify that they are deleted.
- This is validated to work.
=> CAMS-499: Add index of _ts field

test/e2e/playwright/consolidation-orders.spec.ts, user-interface/src/data-verification/DataVerificationScreen.scss, user-interface/src/data-verification/DataVerificationScreen.tsx, user-interface/src/data-verification/TransferOrderAccordion.test.tsx, user-interface/src/data-verification/TransferOrderAccordion.tsx, user-interface/src/data-verification/consolidation/ConsolidationOrderAccordion.test.tsx, user-interface/src/data-verification/consolidation/ConsolidationOrderAccordion.tsx, user-interface/src/data-verification/consolidation/ConsolidationOrderAccordionView.tsx, user-interface/src/data-verification/consolidation/ConsolidationOrderModal.tsx, user-interface/src/data-verification/consolidation/consolidationViewModel.ts, user-interface/src/data-verification/consolidation/consolidationsUseCase.test.ts, user-interface/src/data-verification/transfer/ApprovedTransferOrder.tsx, user-interface/src/data-verification/transfer/SuggestedTransferCases.test.tsx, user-interface/src/data-verification/transfer/SuggestedTransferCases.tsx
Complete the non critical data verification accessibility items (originally on 438)
Testing should be all up to date
=> CAMS-490 more data verification accessibility

backend/lib/adapters/gateways/mongo/offices.mongo.repository.test.ts, backend/lib/adapters/gateways/mongo/offices.mongo.repository.ts, backend/lib/adapters/gateways/mongo/utils/mongo-adapter.ts, backend/lib/use-cases/offices/offices.test.ts, backend/lib/use-cases/offices/offices.ts
We are failing to write to the offices container in prod.
Instead of throwing on the first error, continue processing. We also add context to the errors to hopefully figure out why we are failing.
Automated tests updated.
=> CAMS-502: Keep trying after failure

user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/combobox/ComboBox.test.tsx, user-interface/src/lib/components/combobox/ComboBox.tsx, user-interface/src/lib/components/uswds/Table.scss, user-interface/src/lib/components/uswds/Table.test.tsx, user-interface/src/lib/components/uswds/Table.tsx, user-interface/src/my-cases/MyCasesScreen.tsx, user-interface/src/search-results/SearchResults.tsx, user-interface/src/search/SearchResultsHeader.tsx, user-interface/src/search/SearchResultsRow.tsx, user-interface/src/search/SearchScreen.scss, user-interface/src/search/SearchScreen.tsx, user-interface/src/staff-assignment/header/StaffAssignmentHeader.test.tsx, user-interface/src/staff-assignment/row/StaffAssignmentRow.test.tsx
Non critical case search accessibility
Test coverage added where needed.
Several items on the list were already previously fixed
=> Cams 434 case search accessibility

backend/lib/controllers/case-notes/case.notes.exception.test.ts
There is a failing test.
Fix the test.
Update the test.
=> CAMS-493: Fix failing test

user-interface/.pa11yci, user-interface/src/case-detail/panels/CaseNotes.tsx, user-interface/src/lib/components/uswds/Input.test.tsx, user-interface/src/lib/components/uswds/Input.tsx
Jira ticket: CAMS-504
- clear input value button does not show unless input provided 
- fixed wording on Add Note button and Note Titles
- added condition on clear icon in Input for value
- fixed H4 note titles to have aria Label
- fixed wording on submit button
- updated tests accordingly
- ran locally and validated
=> CAMS-504 Fix Accessibility issues

user-interface/src/lib/components/uswds/Input.tsx
Fix small accessibility issue on Input component
=> CAMS-504 Small accessibility fix for Input component

backend/lib/factory.ts, backend/lib/testing/mock-gateways/mock-mongo.repository.ts, backend/lib/use-cases/orders/orders.test.ts, user-interface/src/admin/AdminScreen.tsx, user-interface/src/admin/privileged-identity/PrivilegedIdentity.test.tsx, user-interface/src/admin/privileged-identity/PrivilegedIdentity.tsx
We need to comply with the Definition of Done.
- Rename delete button.
- Add to the success alert.
- Correct logic to determine whether to enable the save button.
- Correctly handle the user repository singleton.
- All automated tests passing.
- Ran locally and validated all changes.
=> CAMS-500: Address definition of done

backend/lib/adapters/gateways/mongo/case-assignment.mongo.repository.ts, backend/lib/adapters/gateways/mongo/cases.mongo.repository.test.ts, backend/lib/adapters/gateways/mongo/cases.mongo.repository.ts, backend/lib/adapters/gateways/mongo/orders.mongo.repository.ts, backend/lib/adapters/gateways/mongo/utils/mongo-adapter.ts, backend/lib/adapters/gateways/mongo/utils/mongo-query-renderer.ts, backend/lib/controllers/cases/cases.controller.test.ts, backend/lib/controllers/cases/cases.controller.ts, backend/lib/humble-objects/mongo-humble.ts, backend/lib/query/query-builder.ts, backend/lib/testing/local-data/local-cases-repository.ts, backend/lib/testing/mock-gateways/mock-mongo.repository.ts, backend/lib/use-cases/cases/case-management.test.ts, backend/lib/use-cases/cases/case-management.ts, backend/lib/use-cases/gateways.types.ts, common/src/api/pagination.ts, common/src/api/search.ts, user-interface/src/lib/components/Header.tsx, user-interface/src/lib/components/uswds/Pagination.tsx, user-interface/src/lib/components/uswds/UnboundedPagination.tsx, user-interface/src/lib/hooks/UseFeatureFlags.ts, user-interface/src/lib/models/api2.ts, user-interface/src/lib/testing/mock-api2.ts, user-interface/src/my-cases/MyCasesScreen.tsx, user-interface/src/search-results/SearchResults.tsx, user-interface/src/search/SearchScreen.test.tsx, user-interface/src/search/SearchScreen.tsx
WIP
- Handle cosmos case search functionality replacing dxtr case search
- handle pagination components
- Handle cosmos search functionality
- handle pagination components
- ran application locally and verified search and pagination functionality
=> CAMS-421  cosmos search

backend/lib/adapters/gateways/mongo/cases.mongo.repository.test.ts, user-interface/src/lib/components/uswds/Pagination.test.tsx, user-interface/src/lib/components/uswds/Pagination.tsx, user-interface/src/search-results/SearchResults.test.tsx
- WIP: move from DXTR calls to Cosmos Mongo calls, we need to handle pagination differenly, these are the fixes
- modified pagination component to handle bounded pagination properly
- simplified pagination component, and made it more readable
- brought testing coverage of frontend pagination component to 100%
This is branch took care of the frontend pagination for the dxtr pipeline branch
N/A
=> CAMS-421 Search Pagination wrapup

test/e2e/playwright/auth-setup.ts, test/e2e/playwright/consolidation-orders.spec.ts, test/e2e/playwright/fixture/urlQueryString.ts, test/e2e/playwright/transfer-orders.spec.ts, user-interface/src/App.tsx, user-interface/src/admin/AdminScreen.tsx, user-interface/src/data-verification/DataVerificationScreen.test.tsx, user-interface/src/data-verification/DataVerificationScreen.tsx, user-interface/src/lib/components/GoHome.tsx, user-interface/src/lib/components/NotFound.test.tsx, user-interface/src/lib/hooks/UseCamsNavigator.test.tsx, user-interface/src/lib/hooks/UseCamsNavigator.ts, user-interface/src/login/AccessDenied.tsx, user-interface/src/login/Session.tsx, user-interface/src/login/SessionEnd.tsx, user-interface/src/login/broadcast-logout.ts, user-interface/src/login/http401-logout.ts, user-interface/src/login/inactive-logout.ts, user-interface/src/router.test.tsx
Jira ticket: CAMS-515 && 513
The changes we introduced has altered the way session routes the browser and redirects the page. This was not previously corrected in the e2e tests so they continued to fail/
- Update routing to prevent redundant routing
- Correct previously improper routing
- Update E2E tests to properly exercise functionality
- ran through a deployment
- We are still seeing session being cleared when the user directly manipulates the url within mock mode. This is specific to the hosted application, locally it seems to be okay.
=> updated e2e tests to reflect our new changes

backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, common/src/cams/cases.ts, ops/cloud-deployment/lib/cosmos/mongo/cosmos-collections.bicep, ops/cloud-deployment/params/ustp-cams-mongo-collections.parameters.json
We want the query to be performant.
Add an index for the cases collection to aid in searching.
We will deploy to staging and validate there.
=> Add an index for our case search

backend/lib/adapters/gateways/mongo/cases.mongo.repository.test.ts, backend/lib/adapters/gateways/mongo/cases.mongo.repository.ts, backend/lib/adapters/gateways/mongo/utils/mongo-adapter.test.ts, backend/lib/adapters/gateways/mongo/utils/mongo-adapter.ts, backend/lib/adapters/gateways/mongo/utils/mongo-query-renderer.test.ts, backend/lib/adapters/gateways/mongo/utils/mongo-query-renderer.ts, backend/lib/query/query-builder.ts, user-interface/src/search/SearchResultsHeader.tsx, user-interface/src/search/SearchResultsRow.tsx, user-interface/src/staff-assignment/row/StaffAssignmentRow.tsx
Added sorting to paginated aggregate in cosmos.
Addition of sorting for aggregation
For now, sorting fields are hardcoded.  Will probably need to be modified once the case number indexes are added to cosmos.
Testing has not been written yet.  Needs tests before merge.
=> CAMS-421 case search sorting

backend/lib/adapters/gateways/mongo/cases.mongo.repository.ts
Fix case number search logic in the API
* Replaced the bad logic which depended on division codes
=> CAMS-421 Fix case number search logic in the API

.github/workflows/reusable-deploy.yml, backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/main.bicep, ops/scripts/pipeline/azure-deploy.sh
Bring back the changed related to functionapp scalig
- added scaling to function app service plans
- properly split out functionapps into two different app service plans so they can scale independently
- adding scaling to dataflows and api functionapps
deployed 
- This will require deletion and recreation of resources
=> CAMS-421 Handle functionapp scaling

.github/workflows/sub-deploy-code-slot.yml, backend/lib/adapters/gateways/mongo/cases.mongo.repository.ts, backend/lib/adapters/gateways/mongo/utils/mongo-adapter.ts, backend/lib/use-cases/gateways.types.ts, user-interface/src/search-results/SearchResults.tsx, user-interface/src/staff-assignment/screen/StaffAssignmentScreen.test.tsx, user-interface/src/staff-assignment/screen/StaffAssignmentScreen.tsx
Fix the filter of search cases to exclude child cases on consolidations
- update query used to get childconsolidations
- update tests
- ran locally and verfied
- deployed*
=> CAMS-421 consolidation filter fix

.github/workflows/continuous-deployment.yml, .github/workflows/reusable-deploy.yml, ops/cloud-deployment/backend-api-deploy.bicep, ops/cloud-deployment/dataflows-resource-deploy.bicep, ops/cloud-deployment/lib/network/ustp-cams-network.bicep, ops/cloud-deployment/main.bicep, ops/scripts/pipeline/azure-deploy.sh
We were note using the proper plan type for our Azure Functions. So we needed to switch our Function over to the Elastic Premium Plan dedicated to Azure functions. This incompatibility was causing deployment issues for our function apps.
the specific issue we were seeing, was upon initial deployment the functionapps were successfully created in the App Service Plan. Upon subsequent deployment the error we received was 'App Service Plan must not contain functionapps'
- split data flows resource deployment into a separate file
- updated data flows and api function apps to use EP1 skus
- updated our deployment workflow to properly handle these changes
- ran workflow multiple times*
- tesed application to see if scaling occurs properly
We will need to remove these vars from the …
=> CAMS-421 Azure Functions Plan update

backend/function-apps/dataflows/import/migrate-cases.ts, backend/lib/use-cases/dataflows/export-and-load-case.ts, common/src/queue/dataflow-types.ts
Process DLQ events in the case migration
Added RETRY and HARD_STOP queues and retry logic.
Added additional error logging
None
=> CAMS-421 Add retry logic to DLQ events

backend/function-apps/dataflows/import/migrate-cases.ts
Stop processing cases not found in DXTR
Return early if a case is not found.
Testing in STG
=> CAMS-421 Stop processing cases not found in DXTR

backend/function-apps/dataflows/dataflows.ts, backend/function-apps/dataflows/import/migrate-cases.ts, backend/function-apps/dataflows/import/sync-cases.ts, backend/lib/use-cases/dataflows/export-and-load-case.test.ts, backend/lib/use-cases/dataflows/export-and-load-case.ts, backend/lib/use-cases/dataflows/sync-cases.test.ts, backend/lib/use-cases/dataflows/sync-cases.ts
Final user story cleanup.
- Uncomment code to empty the migration table.
- Add the ability to provide an initial transaction id to the sync cases start.
- Increase test coverage.
Automated tests pass.
=> CAMS-421: Definition of done

test/e2e/playwright.config.ts, user-interface/src/login/Session.tsx
Jira ticket: CAMS-525
Turn on playwright tracing for all e2e tests to troubleshoot failing e2e.
Describe what has changed.
=> Troubleshoot failing e2e on main

user-interface/src/trustees/TrusteeCreateForm.scss
Align save button with form inputs
CSS
=> CAMS-582 Aligned save button with form inputs
