.github/workflows/continuous-deployment.yml
.gitignore
.pre-commit-config.yaml
api/.gitignore
api/src/main/java/gov/doj/Application.java
api/src/main/java/gov/doj/ObjectFactory.java
api/src/main/java/gov/doj/Presenter.java
api/src/main/java/gov/doj/RuntimeObjectFactory.java
api/src/main/java/gov/doj/adapters/controllers/CaseListController.java
api/src/main/java/gov/doj/adapters/gateways/AzureSqlGateway.java
api/src/main/java/gov/doj/adapters/gateways/ConnectionManager.java
api/src/main/java/gov/doj/adapters/gateways/LocalPersistenceGateway.java
api/src/main/java/gov/doj/adapters/presenters/JsonPresenter.java
api/src/main/java/gov/doj/entities/Case.java
api/src/main/java/gov/doj/usecases/CasesUseCase.java
api/src/main/java/gov/doj/usecases/PersistenceGateway.java
api/src/test/java/gov/doj/CaseListTest.java
api/src/test/java/gov/doj/TestObjectFactory.java

Adds the use of the Google Java Formatter.
For local development, commits will trigger the formatter if the developer has `pre-commit` installed—which they should.
Files will automatically be fixed by the hook, but will need to be manually committed.
Because `pre-commit.ci` fails to run this check successfully, the `pretty-format-java` hook is skipped for CI in favor of running the [axel-op/googlejavaformat-action@v3 GitHub Action](https://github.com/axel-op/googlejavaformat-action). 
> Note:
> We should not be relying on either pre-commit.ci or Github Actions to run our hooks, rather they are performed on GitHub as a failsafe.
The Action should automatically fix files and push a commit.

111: Add pre-commit-java hooks

---

README.md

Adds clarification for ensuring that git hook is set up properly for pre-commit.

111: Add instructions for validating pre-commit git hook

---

CONTRIBUTING.md
LICENSE.md

Add CC0 license to LICENSE.md
Add CONTRIBUTING.md with disclaimer of waiver of rights pursuant to the CC0 license
The text used comes from a couple of 18f sources, combining a couple of things from [the 18f.gsa.gov license](https://github.com/18F/18f.gsa.gov/blob/main/LICENSE.md) and the markdown from [the 18F Open Source Policy](https://github.com/18F/open-source-policy/blob/master/LICENSE.md).
The summary can be found on [the Creative Commons](https://creativecommons.org/choose/zero/) website.
As was done on [the 18f.gsa.gov license](https://github.com/18F/18f.gsa.gov/blob/main/LICENSE.md), we've added a disclaimer to the contribution guidelines to inform contributors of their waiver of rights to contributions.
USTP is requesting an email address be created for the product. Once that …

106: Add CC0 license

---

.pre-commit-config.yaml
user-interface/package-lock.json

If you delete `package-lock.json` and generate a new one, then the `end-of-file-fixer` pre-commit hook stops you from committing the file without first adding a newline to the end. 
This particular file is unnecessary to check so we can just ignore it.

Ignore package-lock.json on pre-commit

---

.github/workflows/continuous-deployment.yml
.github/workflows/veracode-dast-scan.yml

Disable scans temporarily while awaiting procurement
* Set `if: ${{ false }}` for all relevant steps in continuous-deployment
* Removed dependencies on downstream jobs
* Set the DAST portion to run on Feb 31 only
Make sure we remember to set values back to original when we're ready to reenable.

CAMS-69 temporarily disable scans

---

.secrets.baseline
backend/functions/factory.ts
backend/functions/lib/adapters/gateways/mock-pacer-token-secret.gateway.ts
backend/functions/lib/adapters/gateways/pacer-login.test.ts
backend/functions/lib/adapters/gateways/pacer-login.ts
backend/functions/lib/adapters/gateways/pacer-token-secret.interface.ts
backend/functions/lib/adapters/gateways/pacer.api.gateway.test.ts
backend/functions/lib/adapters/gateways/pacer.api.gateway.ts

Adds a `MockPacerTokenSecretGateway` implementation of `PacerGatewayInterface` which can be used instead of mocks. The mocks were not working as intended. This approach allows for us to inject the appropriate implementation into `PacerLogin` via constructor injection.

CAMS-39: Fix broken tests

---

backend/functions/lib/adapters/gateways/azure-pacer-token-secret.gateway.ts

Use the same name for the environment variable as it is defined in `continuous-deployment.yml`.

CAMS-39: Use correct environment variable name

---

backend/functions/lib/adapters/gateways/cases.local.gateway.test.ts
backend/functions/lib/adapters/gateways/cases.local.gateway.ts
backend/functions/lib/adapters/gateways/mock-pacer.api.gateway.ts
backend/functions/lib/adapters/gateways/pacer.api.gateway.chapter15.date.test.ts
backend/functions/lib/adapters/gateways/pacer.api.gateway.test.ts
backend/functions/lib/adapters/gateways/pacer.api.gateway.ts
backend/functions/lib/adapters/utils/date-helper.test.ts
backend/functions/lib/adapters/utils/date-helper.ts
backend/functions/lib/use-cases/chapter-15.case-list.test.ts

Add a helper method to standardize how we get the strings we use from an instance of the `Date` class.
I'm sure we will not need to be processing valid dates that do not have 4-digit years, but dates prior to the year 1000 get a leading `0` in the ISO String, and dates following the year 9999 get a leading `+0`. If for some reason we wanted to be able to display these dates, we would perhaps want to change the method to do more than take the part of the ISO string before the `T`.
This is not strictly necessary, I just thought it might be nice to have.

CAMS-97: Add getCamsDateStringFromDate method

---

.github/workflows/continuous-deployment.yml
backend/functions/package-lock.json
backend/functions/package.json
user-interface/src/models/api.ts

[Dependabot identified](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/security/dependabot/12) a vulnerable package—@opentelemetry/instrumentation@0.40.0.
The vulnerable package is a transitive dependency, so we override it with the latest version.
The change was [deployed here](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/5823858267). As I understand it, the application insights configuration is not currently producing results that can be validated.
Updated other npm packages via `npm update` and one that was identified by `npm outdated`.
I also discovered that `continuous-deployment.yml` didn't get the new environment variable names for the frontend to know the url for the backend, so updated those.
And by accident I …

CAMS-120 Dependabot Opentelemetry

---

.github/workflows/continuous-deployment.yml
backend/functions/attorneys/attorneys.function.ts
backend/functions/cases/cases.function.ts
backend/functions/package.json
backend/functions/users/users.function.ts
docs/running.md
ops/cloud-deployment/app-insights/app-insights.bicep
ops/cloud-deployment/app-insights/diagnostics-settings-appi.bicep
ops/cloud-deployment/app-insights/diagnostics-settings-func.bicep
ops/cloud-deployment/app-insights/diagnostics-settings-webapp.bicep
ops/cloud-deployment/backend-api-deploy.bicep
ops/cloud-deployment/frontend-webapp-deploy.bicep
user-interface/src/ApplicationInsightsService.tsx

Branch off of CAMS-103-frontend-logging to test out some changes in a separate environment without impacting the last known good.
- Leverage **APPLICATIONINSIGHTS_CONNECTION_STRING** instead of the using **APPINSIGHTS_INSTRUMENTATIONKEY**
- Handle corner cases when provisioning Application Insights resource and code clean up in bicep.
WIP

CAMS-103 Refactoring related to application insights setup

---

.github/workflows/continuous-deployment.yml
.gitignore
architecture/cams.dsl
architecture/export-architecture-diagrams.sh
docs/architecture/_sidebar.md
docs/architecture/diagrams/cams-containers.md
docs/architecture/diagrams/cams-context.md
docs/architecture/diagrams/cams-functions-api-components.md
docs/architecture/diagrams/cams-webapp-components.md
docs/architecture/diagrams/cams-webapp-with-functions-api.md
docs/index.html

Adds diagrams as code to support threat modeling.
We define the architecture using the [Structurizr domain-specific-language](https://github.com/structurizr/dsl/tree/master/docs/cookbook/introduction) and then use an [accompanying CLI](https://github.com/structurizr/cli) to output [Mermaid](https://mermaid.js.org/). Then we copy the Mermaid code into markdown files for inclusion in our Docsify pages.
GitHub Pages is currently set to deploy from this branch and behavior can be validated [here](https://us-trustee-program.github.io/Bankruptcy-Oversight-Support-Systems/#/).
This approach allows us to generate several levels of diagram that might be used for different purposes. This is called the C4 Model and you can learn more [here](https://c4model.com/).

Cams 109 add architecture diagram

---

docs/ops.md
ops/helper-scripts/data/import-data.sh

Need to load test data to new sql server database table
- Helper script to invoke bcp utility to load data from file
- Manually invoked from local machine running OS X to load data for AO_CS table
- The ideal import file would be a pipe (|) delimited data file, which will reduce conflicts with some common symbols that may appear in the data like commas and tabs.

CAMS-93 Script to import data from file to sqlserver table

---

docs/running.md

Fixing a mistake I made in documentation
Replace TLD with FQDN in `docs/running.md`.

Fix incorrect term usage

---

backend/functions/lib/adapters/gateways/cases.dxtr.gateway.ts
backend/functions/lib/adapters/gateways/cases.local.gateway.ts
backend/functions/lib/adapters/utils/date-helper.test.ts
backend/functions/lib/adapters/utils/date-helper.ts
user-interface/src/components/CaseAssignment.tsx

The date format coming from PACER was `yyyy-MM-dd`, but from DXTR is an ISO date string. Our frontend code was splitting the `date filed` on the `-` and as a result was displaying a messed up ISO date instead of the `MM-dd-yyyy` format we were looking for.
We format the date filed field in our query from DXTR. For the local gateway which was originally based on PACER data, we leave the source data the same, but add a helper function which converts the date. 
Added a test for the new helper function. Validated the date format running locally with both the DXTR and local data sources.
If we find the new helper function useful for more use cases, some validation would be needed. For now, it is only being used on hard coded data, so that would add unnecessary complexity.

Cams 98 format date

---

backend/functions/lib/adapters/gateways/cases.dxtr.gateway.ts
user-interface/src/App.scss
user-interface/src/components/CaseAssignment.scss
user-interface/src/components/CaseAssignment.test.tsx
user-interface/src/components/CaseAssignment.tsx
user-interface/src/components/HeaderNavBar.scss
user-interface/src/components/HeaderNavBar.tsx

Reformat the Assigned Cases screen into 2 tables to split view between those assigned and unassigned. 
- Split Assignment screen into 2 tables: Assigned and Unassigned
- Added animation so that the newly assigned case is highlighted in the Assignment table.
Tests for new functionality not yet written but overall test coverage is still above 90%.
Questions for UX have come up that will need to be discussed with Phoenix and team:
1. Shoudl the tables be scrollable and how many items should be displayed per table / or what should the height of the table be.
2. How long should animation take
3. Is the look of the animation okay?

CAMS-83: Split attorney screen

---

backend/functions/case-assignments/case.assignment.function.ts
backend/functions/case-assignments/function.json
backend/functions/lib/adapters/controllers/case.assignment.controller.test.ts
backend/functions/lib/adapters/controllers/case.assignment.controller.ts
backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.ts
backend/functions/lib/adapters/gateways/case.assignment.local.repository.ts
backend/functions/lib/adapters/types/attorney.class.ts
backend/functions/lib/adapters/types/case.attorney.assignment.ts
backend/functions/lib/cosmos-humble-objects/fake.cosmos-client-humble.ts
backend/functions/lib/interfaces/case.assignment.repository.interface.d.ts
backend/functions/lib/use-cases/attorneys.ts
backend/functions/lib/use-cases/case.assignment.ts
backend/functions/lib/use-cases/chapter-15.case-list.test.ts
backend/functions/lib/use-cases/chapter-15.case-list.ts
user-interface/src/components/AssignAttorneyModal.tsx
user-interface/src/components/CaseAssignment.tsx
user-interface/src/type-declarations/attorneys.ts

We had generated random numbers for case count on the assignment modal and needed to get real numbers.
When we retrieve the list of attorneys from the backend we now also get a count of how many chapter 15 case assignments they have.
Validated locally by hitting the databases deployed in Azure.
Unit testing included.
We are just returning an empty array from `case.assignment.local.repository.ts` (for local development) when we get the assignments for an attorney. We need to decide on an approach for this to let us develop locally without hitting deployed databases.
Renamed `attorneyName` to `name` in the `CaseAttorneyAssignment` class—and consequently the Cosmos DB data for the `assignments` container.

CAMS-148: Get count of cases assigned to attorneys

---

.github/workflows/continuous-deployment.yml
ops/helper-scripts/dev-add-allowed-ip.sh

Pipeline run experiencing intermittent smoke test and integration failures. Determine that failure is most likely cause by non-unique names created for allow rules for making network request to webapp and api. The other cause is that integration test executes before the webapp is online.
- Modify approach to add rule to allow target GHA runner access to execute test request to webapp and api. Rule name created should be unique
- Move integration test after smoke test. 
- Manual execution of pipeline with all tests passing

CAMS-143 Fix post deployment test failures

---

user-interface/src/components/CaseAssignment.test.tsx
user-interface/src/components/CaseAssignment.tsx

The purpose of this PR is to add functionality to hide the unassigned cases table when there are 0 unassigned cases
- Addition of hide unassigned cases table functionality
- addition of test cases
The app was run locally and assigned all unassigned cases, confirming the unassigned table is not visible.

CAMS-157: Hide unassigned table when its empty

---

user-interface/src/components/Home.tsx

Set the home view to be the case assignment screen.
Add the CaseAssignment component to the Home component.
Ran frontend locally, validated that the Case Assignment screen is displayed as the home page.

CAMS-47: Set the case assignment screen as the home screen

---

backend/functions/lib/adapters/gateways/cases.dxtr.gateway.test.ts
backend/functions/lib/adapters/gateways/cases.dxtr.gateway.ts
backend/functions/lib/adapters/types/cases.d.ts
user-interface/src/components/CaseDetail-test-without-dismiss-date.test.tsx
user-interface/src/components/CaseDetail.test.tsx
user-interface/src/components/CaseDetail.tsx
user-interface/src/type-declarations/chapter-15.d.ts

Get Dismissed date to display on case details screen.
Added Dismissed Date to both the back and and front end.  On Front end, if no case dismissed date is returned from the back end, then it will not be displayed.
Testing coverage requirements met.

Cams 169 get dismissed date

---

user-interface/package-lock.json
user-interface/package.json

We were experiencing an issue where any time `npm install` was run for the frontend, if a package-lock.json was present a new file would be generated that was out of sync with the package.json file.
Removed the preinstall script which [was added back when](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/pull/47/files) we were still using `create-react-app`. We also remove the recent additions to the overrides.
Ran several iterations of `npm i` and `npm ci` along with running `npm test` and `npm run build`. None of the previous issues were observed.

CAMS-193 package lock experiment

---

user-interface/src/components/AssignAttorneyModal.tsx
user-interface/src/components/uswds/modal/Modal.test.tsx
user-interface/src/components/uswds/modal/Modal.tsx

Fix accessibility issue with tabbing out of the modal going back to the document.  
We added event handlers to the modal close button and the modal body container that cause the tab stops to loop back to the first or last element in the modal, while the modal is open.
Test coverage is already above 90%, barely. 
Testing has proven difficult for this... yet again.  It seems the testing libraries don't handle tabbing and focus events properly or at all in their jestdom.  I began a test, but it needs work to get it to pass.  I'm not sure we'll be able to successfully test these changes in this branch.

Cams 193 contain tab within modal

---

.github/workflows/continuous-deployment.yml

Current SAST scan breaks build where appropriate, but does not upload results to Veracode. These changes will add another scan job that scans & uploads, but won't break build.
* Add GitHub workflow job to run the scan & upload task
* Updated secrets to use service account
See action [completed successfully here (when commented out `if github.ref =='refs/heads/main`)](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/6628569957) and that it [does not run when that is uncommented](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/6629259027).
Verified that scan results appeared in Veracode platform.
May still want to have Veracode review our workflow to see if any optimizations could be achieved.

CAMS-193: adds sast scan upload task to only run on main

---

ops/cloud-deployment/frontend-webapp-deploy.bicep

Resolves the following CWE-757
- Update bicep deployment to set min cipher for deployments using premium plans
- Verify bicep deployment with Basic and Premium plan types
- This Azure feature is still in Preview and is only available for premium plan types or higher.

CAMS-140 Automate setting minimum TLS cipher suite

---

user-interface/public/nginx.conf

See issue VER-10 for details
Set `X-Frame-Options` response header to `DENY`
- Checked issued resolved with header updates via securityheaders.com using both latest Chrome and Edge browser
- Deployed branch updates to new environment and verified with Veracode DAST scanning.

VER-10 Set X-Frame-Options response header

---

backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts
backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts
backend/functions/lib/adapters/types/cases.d.ts
backend/functions/lib/testing/mock-data/cases.mock.json
dev-tools/test-data/domain/court.ts
dev-tools/test-data/fixtures/courts.ts
dev-tools/test-data/fixtures/lib/common.ts
dev-tools/test-data/tables/AO_GRP_DES.ts
dev-tools/test-data/tables/AO_REGION.ts
dev-tools/test-data/tables/common.ts
user-interface/src/components/CaseDetail.scss
user-interface/src/components/CaseDetail.test.tsx
user-interface/src/components/CaseDetail.tsx
user-interface/src/models/chapter15-mock.api.cases.ts
user-interface/src/type-declarations/chapter-15.d.ts

Add region ID to case detail screen.
Modified case detail query against DXTR database to join on AO_GRP_DES to return REGION_ID.
Modified case detail screen to show the region ID.
Reformatted the region ID to remove leading zeros which are present in the database.
Added unit tests in API to confirm region ID is returned from DXTR gateway.
Added unit tests in UI to confirm the presence of the region ID and that it is properly formatted on screen.

CAMS-209 Add USTP region ID to case details

---

backend/functions/lib/adapters/gateways/cases.local.gateway.ts
user-interface/src/components/CaseAssignment.scss
user-interface/src/components/CaseAssignment.tsx
user-interface/src/components/CaseDetail.tsx

Only the case details screen after data was loaded was utilizing the 12 column grid and we wanted everything to do so.
- Add grid to case assignment screen during loading and after the list is displayed
- Add grid to case detail screen during loading
- Make case details take up the entirety of the 12 columns (with 1 column empty on either side)
Validated that the screens look correct at various sizes of the browser.
- Added local gateway data to the backend
Responsiveness is not fully defined yet. We need to know what effect break points should have on the display.

CAMS-230: Finish 12 column grid transition

---

user-interface/.pa11yci
user-interface/src/case-detail/CaseDetailScreen.tsx
user-interface/src/case-detail/panels/CaseDetailBasicInfo.tsx
user-interface/src/case-detail/panels/CaseDetailCourtDocket.scss
user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx
user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx
user-interface/src/lib/components/uswds/Alert.tsx
user-interface/src/lib/type-declarations/chapter-15.d.ts

Display Docket Entries in the Case Detail screen court docket panel.
* Court Docket screen added to Pa11y.
* Updated CaseDetailScreen.tsx to support Court Docket entries and renamed the basic info component from CaseDetailContents to CaseDetailBasicInfo (or something like that)
* Populated Court Docket screen according to the Figma
* Wrote tests
Coverage is above 90%

CAMS-219 display docket record

---

backend/functions/attorneys/attorneys.function.ts
backend/functions/case-assignments/case.assignment.function.ts
backend/functions/cases/cases.function.ts
backend/functions/lib/adapters/gateways/debtor-type-gateway.test.ts
backend/functions/lib/adapters/gateways/debtor-type-gateway.ts
backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts
backend/functions/lib/adapters/gateways/dxtr/dxtr.gateway.helper.test.ts
backend/functions/lib/adapters/gateways/dxtr/dxtr.gateway.helper.ts
backend/functions/lib/adapters/gateways/petition-gateway.test.ts
backend/functions/lib/adapters/gateways/petition-gateway.ts

Jira ticket: CAMS-243
Case detail lookup fail to show on case detail screen.
Revised logic to not throw CamsError when a lookup key is not found in the label mappings
and instead return an 'unknown' label for a more graceful failure.
Updated unit tests to handle lookup table misses.

CAMS-243 Fixed logic make DXTR petition and debtor type lookup resilient

---

backend/functions/lib/adapters/gateways/dxtr/case-docket.dxtr.gateway.ts

The case docket screen does not render when a summary text is null in the docket
Added null checks in the SQL to ensure text is always returned from the API.
Added the data integrity issue to a case in the Flexion DXTR database to reproduce the error then tested to ensure the page renders as expected.

CAMS-250 null summary bug

---

docs/_sidebar.md

The link in the documentation to the contributing markdown was broken.
Point to the new contributing directory for the contributing documentation.
- Validated that the docs work as expected locally.
- [Deployed this branch](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/7006887038).

Fix contributing link in docsify

---

user-interface/src/App.tsx
user-interface/src/case-detail/CaseDetailScreen.scss
user-interface/src/case-detail/CaseDetailScreen.tsx
user-interface/src/case-detail/panels/CaseDetailHeader.scss
user-interface/src/case-detail/panels/CaseDetailHeader.test.tsx
user-interface/src/case-detail/panels/CaseDetailHeader.tsx
user-interface/src/case-detail/panels/CaseDetailNavigation.d.ts
user-interface/src/case-detail/panels/CaseDetailNavigation.scss
user-interface/src/case-detail/panels/CaseDetailNavigation.test.tsx
user-interface/src/case-detail/panels/CaseDetailNavigation.tsx
user-interface/src/lib/hooks/UseFixedPosition.ts

Case Details Screen header, which contains the Case Title, number, location, and chapter number and type, should become fixed to the top of the screen whenever the screen is scrolled to the point where the header touches the top of the browser window.
Likewise the Case Detail Navigation menu at the left should become fixed.
The header and navigation should then go back to normal once the screen is scrolled down enough for the BLUE app header peaks out under the Case Details Screen Header.
A lot... ?  Handling for screen manipulation via useEffect and watching scroll events to either render a new component to replace one on screen, or add css classes to components.  The animation and style changes are handled in SCSS files.
Testing was added to ensure that components were properly replaced …

CAMS-246 view case header while scrolling

---

backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts
common/src/feature-flags.ts
user-interface/src/case-assignment/AssignAttorneyModal.tsx
user-interface/src/case-assignment/CaseAssignmentScreen.test.tsx
user-interface/src/case-assignment/CaseAssignmentScreen.tsx
user-interface/src/lib/hooks/UseFeatureFlags.ts
user-interface/src/lib/models/chapter15-mock.api.cases.ts

For demo purposes, we wanted the cases displayed in the Case Assignment screen to be more likely to have viewable documents. 
- Adds a feature flag to enable chapter 11. When set, we retrieve the top 10 chapter 11 results in addition to chapter 15 (and chapter 12 if it is enabled).
- Modifies the query to get the case list to order by filed date, newest first.
- Case Assignment screen no longer changes based on feature flags (the Assign Attorney modal still does)
- Updated automated tests.
- Modified some Flexion data to reflect some chapter 11 data when enabled.
- Deployed to USTP environment and validated view.

CAMS-257 get cases with documents

---

user-interface/src/case-detail/CaseDetailScreen.tsx
user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx
user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx

Jira ticket: CAMS-259
When a case has a large number of docket entries and the call to get the docket record takes sufficiently longer than the call to get basic info, we were momentarily displaying the alert as if the case had no docket entries.
When calculating `hasDocketEntries` for the docket panel, we passed `false` if the array did not exist yet. We could have passed true until it existed and then calculate it based on length, but we preferred to use an `isDocketLoading` state variable to be passed in the properties as well. 
- Updated automated tests
- Triggered the error by temporarily adding a long wait to the call to docket
- Validated that behavior was as observed in USTP environment
- Validated that after the changes, no alert was displayed if docket entries exist, but is …

CAMS-259: Add state variable for tracking docket api call

---

user-interface/src/case-detail/CaseDetailScreen.tsx

Screen readers were not reading the label for the document number filter.
Set the `htmlFor` correctly (i.e. the `id` of the input, not the `name`).
Ran a screen reader locally and validated that the label is now read.

CAMS-255: Fix label for document-number-search-field

---

ops/cloud-deployment/frontend-webapp-deploy.bicep

Ensure application insights is configured correctly for USTP and correct typo in APPLICATIONINSIGHTS_CONNECTION_STRING within frontend deployment
correct typo in APPLICATIONINSIGHTS_CONNECTION_STRING within frontend deployment
Validated logs coming through on our side and the USTP side
Future improvement, we might need to change the threshold on alerts so we do not get them as frequently when we do not need to address them.

corrected typo in APPI connection string

---

.github/workflows/continuous-deployment.yml

Add logic to retry deployment steps when they fail for webapp or function deployment
- addition of steps to run retries when deploying frontend or backend components fails
- ran workflow and tested logic
- deployed app environment to allow testing on an active environment
We also have the option of using a separate github job that:
- runs on job failure
- runs **gh run rerun RUN_ID --failed**
-- runs only failed jobs

CAMS-146: frontend deployment retry

---

user-interface/.pa11yci
user-interface/src/case-detail/CaseDetailScreen.scss
user-interface/src/case-detail/CaseDetailScreen.test.tsx
user-interface/src/case-detail/CaseDetailScreen.tsx
user-interface/src/case-detail/panels/CaseDetailHeader.scss
user-interface/src/case-detail/panels/CaseDetailNavigation.tsx
user-interface/src/lib/components/uswds/DateRangePicker.scss
user-interface/src/lib/components/uswds/DateRangePicker.tsx
user-interface/src/styles/theme.scss

Re-enable pa11y tests. Fix side nav styling.
* Refactored logic using Array.prototype.findLast
* Re-enabled case docket pa11y test
* Modified styling of docket search components to slip beneath side navigation.
Visually verified style changes. Ran pa11y tests to confirm re-enabled test worked. Existing unit test for bounds function proved the refactor did not change the output of the function.

CAMS-254 Re-enable pa11y tests. Fix side nav styling.

---

.github/workflows/continuous-deployment.yml

Veracode Failing on pipeline Scans
- Added continue on fail for the pipeline scan step within the workflow
- removed dependency on pipeline-scan step from the deploy step
this solution is temporary until we figure out what is going on with Veracode
- solution allows workflow to complete should the pipeline-scan fail 
- ran workflow and verified it pushes past pipeline scan step

Cams 293 fix veracode scan

---

backend/functions/lib/testing/mock-data/attorneys.mock.ts
backend/functions/lib/testing/mock-data/case-history.mock.ts

Removing Richard C Morrissey from the Attorneys to reduce the risk of upsetting individuals when they are testing the application. 
Removed Richard from the Attorney list. Changed a test that was assigning Richard.

Remove richard morrissey

---

user-interface/src/App.test.tsx
user-interface/src/App.tsx
user-interface/src/case-assignment/AssignAttorneyModal.test.tsx
user-interface/src/case-assignment/CaseAssignmentScreen.test.tsx
user-interface/src/case-detail/CaseDetailScreenSortAndFilter.test.tsx
user-interface/src/lib/components/ScrollToTopButton.tsx
user-interface/src/lib/components/uswds/Checkbox.test.tsx
user-interface/src/lib/components/uswds/DateRangePicker.test.tsx
user-interface/src/lib/components/uswds/Header.test.tsx
user-interface/src/lib/components/uswds/modal/Modal.test.tsx
user-interface/src/review-orders/ReviewOrdersScreen.test.tsx
user-interface/src/router.test.tsx

Tests were hanging in the CI/CD pipeline.
We remove `userEvent` and `fireEvent` actions from `act()` and `waitFor()`. `act()` is unnecessary because `testing-library` already wraps `render` and these events in `act()`. We suspect the actions being triggered from within `waitFor()` was causing a memory leak.
We also found after this change that the ScrollToTopButton test failed because the way the button was scrolling to the top was not triggering the `onScroll` function during tests. We now trigger an event on the app rather than directly editing the scroll position.
We ran the tests locally several ways and the failure—which had become constant—went away in the CI/CD pipeline.

CAMS-262 fix tests

---

backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.test.ts
backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.ts

Temporarily limit order results in the USTP environment from DXTR to chapters enabled by feature flags from region 2.
Added additional chapter and region predicates to the order SQL query.
Added unit test to exercise the feature flag logic. Manually debugged the app to observe changes to the SQL statement.

CAMS-262 limit orders chapter region

---

backend/functions/lib/adapters/gateways/dxtr/orders.dxtr.gateway.ts

The documents query had some invalid sql.
Remove the ORDER BY in the sub-query, make the aliases match, and add a JOIN to the AO_GRP_DES table.
Ran the query locally against both Flexion and USTP DXTR databases.

CAMS-263 Make the documents query work

---

backend/functions/lib/adapters/gateways/cosmos/cosmos.helper.test.ts
backend/functions/lib/adapters/gateways/cosmos/cosmos.helper.ts
backend/functions/lib/adapters/gateways/orders.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/orders.cosmosdb.repository.ts
backend/functions/lib/testing/cosmos-errors.ts
backend/functions/lib/testing/mock.cosmos-client-humble.ts
backend/functions/lib/use-cases/orders/orders.model.ts

We do not want to create duplicate orders.
- Replace the auto-generated id with a hash of full caseId and order sequenceNumber
- Perform an upsert instead of a create
Ran the manual sync many times with the transaction id override set to 0 and validated that only one of each order existed afterward.

CAMS-263: Perform upsert for orders so we do not duplicate

---

user-interface/src/review-orders/TransferOrderAccordion.test.tsx
user-interface/src/review-orders/TransferOrderAccordion.tsx

Closing the rejection modal did not clear the reason entered.
Upon closing the modal—by any method—we clear the reason.
Put the `Cancel` and `Approve` buttons closer together.
Added new tests to validate the handling of reason.
Verified UX with reduced window size.

Clear rejection reason upon closing the modal

---

.github/workflows/continuous-deployment.yml

Investigate and fix pipeline scan execution in CI pipeline. On findings that are equal and above a Medium, the pipeline should fail.
- Update SAST scan to leverage a Veracode policy
- Include the common module as part of the scan
- Confirm usage of Veracode policy
- Verify that pipeline fails for medium findings with the application of the policy

CAMS-319 veracode fix pipeline scan

---

backend/functions/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts

We are incorrectly excluding cases transferred to another division within the same court.
Modify the exclusion condition to look for both court and division to be the same.
Ran query in USTP environment against the case where we saw the issue.

CAMS-324: Fix same court exclusion

---

user-interface/src/case-assignment/CaseAssignmentScreen.test.tsx
user-interface/src/case-assignment/CaseAssignmentScreen.tsx

Include error handling logic in place of where logging was removed because of a Veracode finding.
- Add error handling logic in case assignment view when attorney api fails
- Update unit tests and mocks for case and attorney api calles
- Passing unit tests and increased code coverage on error handling code blocks

VER-32 Add error handling

---

user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx
user-interface/src/lib/components/IconInput.tsx
user-interface/src/lib/utils/highlight-api.ts

Application crashed when entering in value for docket search in case details view for cases with large number of docket entries. Investigation shows approximately 9k+ docket entries for this particular case and webapp throws a **RangeError** when invoking `handleHighlight`
- Catch error to prevent application to break
- Set a min limit before invoking handleHighlight
- Resolve warning related to IconInput
- Seed database with large number of dockets for case id 96-45961 in test database and confirm that problem can be recreated
- Manually verify fix in deployed webapp 
- Noticed degraded performance with entering text into the search field for cases with large number of dockets. Min search text size is set to 3. This should alleviate the webapp from crashing and a way to improve on this …

CAMS-332 Fix RangeError on docket search

---

user-interface/.pa11yci

This should hopefully fix the failed pa11y test.
Added a click on the Consolidations filter to turn consolidations off during the Pa11y test.  We're expecting only 3 transfer orders and nothing else on screen.
Tests seem to be passing now.

CAMS-270: Added step to order transfer pa11y test

---

user-interface/src/data-verification/ConsolidationOrderModal.tsx

Change modal button label to 'Approve' temporarily until we create the second screen for the modal.
verbiage

CAMS-270: Changed button label in modal to Approve

---

ops/cloud-deployment/ustp-cams-cosmos.bicep

removing unused output from bicep files 
removed unused output from bicep file that was replaced 
Deploy environment without the bicep file output

CAMS 322 remove unused vars from bicep

---

user-interface/src/App.scss
user-interface/src/data-verification/ConsolidationOrderAccordion.tsx
user-interface/src/data-verification/TransferOrderAccordion.scss
user-interface/src/data-verification/TransferOrderAccordion.tsx

Noticed issue with how the `Cancel` and `Approve` buttons get overlay during implementation of test using Cypress. The right gutter column overlay the Approve button and prevented it being clicked by the test framework.
- Modified the grid layout
- Manual inspection
- Confirm passing Cypress test after change

CAMS-269 Fix grid layout for transfer accordian buttons

---

architecture/export-architecture-diagrams.sh
docs/architecture/diagrams/cams-containers.md
docs/architecture/diagrams/cams-context.md
docs/architecture/diagrams/cams-functions-api-components.md
docs/architecture/diagrams/cams-webapp-components.md
docs/architecture/diagrams/cams-webapp-with-functions-api.md
docs/index.html

Our architecture diagrams were not being displayed properly.
- Added a newline after the ```` ```mermaid ```` line
- Added a newline after the ```` ``` ```` line so that pre-commit doesn't have to add it (helps with developer's commit flow
- Updated the mermaid docs themselves
- Modified the Docsify html file a bit which was probably unnecessary, but does update the version of the mermaid plugin we're using
Ran Docsify locally.
While troubleshooting I found that we can use `homebrew` to install the `structurizr-cli` locally rather than needing to manually download the archived `structurizr.sh`. We could also potentially add this step to our GitHub Actions workflow and not need to worry about developers potentially having different versions of structurizr locally.
If you have the …

Add newline after mermaid language tag

---

.github/workflows/continuous-deployment.yml

Fix deployment failure related to empty string passed to database deployment script. This only occurs on main branch.
- Pass expected non-empty string to script
- Update smoke test
- Successful Deploy database step in branch deployment 
Need to verify in main branch CICD workflow

CAMS-345 Fix for missing branch hash id for main CICD deployment

---

ops/scripts/pipeline/check-deploy-bicep.sh

Jira ticket: CAMS-358
Forcing bicep deployment on USTP with var does not evaluate correctly because it is a string vs a boolean variable
added check for string against deployment boolean within check-deploy-bicep.sh
Test on USTP side

added evaluation against string car for deploy_flag

---

backend/functions/cases/cases.function.ts
backend/functions/lib/use-cases/orders/orders.test.ts
backend/functions/lib/use-cases/orders/orders.ts
common/src/cams/orders.ts
common/src/feature-flags.ts
dev-tools/cosmos-records/delete-orders.ts
dev-tools/cosmos-records/sync-orders.ts
user-interface/src/data-verification/ConsolidationOrderAccordion.tsx
user-interface/src/data-verification/ConsolidationOrderModal.test.tsx
user-interface/src/data-verification/ConsolidationOrderModal.tsx
user-interface/src/lib/hooks/UseFeatureFlags.ts

Reject a consolidation order.
* Enable the rejection button in the consolidation order accordion
* Render the rejection modal
* Call the rejection endpoint from the UI
* Update the order buffer in the UI
* Update status on the consolidation order in Cosmos
* Confirm documents are correctly written to Cosmos
* Test coverage above threshold

CAMS-301 Reject consolidation

---

user-interface/src/data-verification/ConsolidationCasesTable.tsx
user-interface/src/data-verification/ConsolidationOrderAccordion.test.tsx
user-interface/src/data-verification/ConsolidationOrderAccordion.tsx

Add docket entries to rejected consolidation accordion content.
Added table from pending content to the rejected content. Dynamically removed the checkboxes used by the pending screen.
Manually tested and reviewed.

CAMS-301 Add docket table to rejected consolidation accordion

---

user-interface/src/case-detail/panels/CaseDetailAssociatedCases.test.tsx
user-interface/src/data-verification/CaseTable.tsx
user-interface/src/data-verification/ConsolidationCasesTable.test.tsx
user-interface/src/data-verification/ConsolidationCasesTable.tsx
user-interface/src/data-verification/ConsolidationOrderAccordion.test.tsx
user-interface/src/data-verification/ConsolidationOrderAccordion.tsx
user-interface/src/data-verification/TransferOrderAccordion.tsx
user-interface/src/lib/components/uswds/Checkbox.test.tsx
user-interface/src/lib/components/uswds/Checkbox.tsx

Provide toggle button to check and uncheck all checkboxes in the consolidations table
- Added a button that selects or deselects all checkboxes.
- The button label changes depending on whether all checkboxes are checked or (some or all) checkboxes are unchecked.
- Updated Checkbox component to add indeterminate state.
- Changed all inputs of type "checkbox" to actual USWDS Checkbox components in the consolidations table.
Testing added or modified to bring coverage above 90%.

CAMS-349: check uncheck all

---

test/e2e/playwright/consolidation-orders.spec.ts

New USWDS Checkbox component cause some issues with E2E testing.
The following is neccessary because the USWDS checkbox input is rendered hidden off-screen.
Therefore playwright can't check the box if it can't see it using the normal page.getByTestId.
So using this method, you can locate the checkbox and fire a click event.
I tried getting the label by test id, but it can't click on the label because the checkbox image is rendered in a css pseudo class, and javascript can not access the pseudo class.
Clicking the label did not seem to fire the click event on the checkbox input.
Instead of the usual `const checkbox = page.getByTestId()` and `checkbox.check()` we need to use the following:
```
await page
.locator(
`input[data-testid="checkbox-case-selection-${pendingConsolidationOrder.id}-ca …
```

CAMS-349 Fixed issues in E2E tests caused by the use of USWDS Checkbox

---

CODEOWNERS

We want the EA team to be required approvers for files affecting deployment in USTP environments.
- Add EA as code owners for all `.bicep` files, and the directories where we store scripts and other files relating to deployment that affect USTP environments.

CAMS-370: Add EA team and general code ownership

---

.github/workflows/sub-security-scan.yml
ops/scripts/utility/clean-all-projects.sh
ops/scripts/utility/clean-install-all-projects.sh
package.json

It would be nice to have a single command available to clean all projects for things like creating a zip file for VeraCode.
- Add a shell script to loop through all npm projects and run their clean script
- Add a shell script to loop through all npm projects and run `npm ci`
- Add top-level npm scripts to call the new shell scripts
Ran the npm script locally.
We could add other similar scripts such as:
- `install:all`
We could also update `build` to utilize a shell script.

CAMS-380: Add clean:all script to the top level package.json

---

.github/workflows/sub-security-scan.yml

We want the deployment to the Flexion environment to fail if any of the security steps fails.
Removed continue on failure condition.

CAMS-380: remove continue on fail condition

---

.github/workflows/update-dependencies.yml
ops/scripts/utility/update-dependencies.sh

- Add `-c` flag to the usage of the script to indicate it is a CI/CD run
- Add a manual trigger of the workflow
- Fix branch name
- Replace usages of `git checkout` with `git switch`
Manual testing already performed of the script, but will need to test the workflow once it is merged to main.

Fix broken update workflow

---

.github/workflows/update-dependencies.yml
ops/scripts/utility/update-dependencies.sh

Add use of a GitHub Action that handles git config including signing the commit.
Hashicorp used to have a fork of the action used here which they have archived and recommended using the base repo. This is a fairly widely used action.

Configure git so the commit will work

---

CODEOWNERS

Jira ticket: CAMS-386
Update EA Ownership of files with only bicep that makes changes to permissions and/or networking
Added bicep files that manipulate permissions or networking to EA ownership for PR review
N/A
Do we want to include parent templates that call child templates? e.g. ustp-cams-cosmos.bicep >> cosmos-account.bicep. do we want to add ustp-cams-cosmos.bicep as well?

CAMS-386: Added bicep files related to networking and permission to EA Ownership

---

.github/workflows/continuous-deployment.yml
.github/workflows/sub-build.yml
user-interface/src/lib/components/Header.scss
user-interface/src/lib/components/Header.tsx
user-interface/src/lib/components/uswds/Banner.scss
user-interface/src/lib/components/uswds/Banner.test.tsx
user-interface/src/lib/components/uswds/Banner.tsx

Jira ticket: CAMS-387
Clearly state environment when the user is not within the production application
- Change color of banner dependent on environment
- Display environment centered within banner for development and staging
- Edited workflow to include CAMS_LAINCH_DARKLY_ENV as an env var
- ran build locally with all 3 LaunchDarkly environments as env var CAMS_LAUNCH_DARKLY_ENV= (development, staging, production) and verified the app functioned as expected
We can modify this however we want. these were just my initial thoughts
We will also need to add the var for CAMS_LAUNCH_DARKLY_ENV to the USTP STG and PRD AzDO variable libraries
- 'staging' within CAMS_STG

CAMS-387: setup clearly visibile environment when not in production

---

.github/workflows/update-dependencies.yml
ops/scripts/utility/audit-comment.md
ops/scripts/utility/audit.sh
ops/scripts/utility/check-outdated.sh
ops/scripts/utility/no-outdated-comment.md
ops/scripts/utility/outdated-comment.md

- Add running of a script to the workflow that will get a list of outdated packages and add a PR comment to automatically inform us of what packages have major updates available.
- Add running of a script that runs `npm audit` against all NPM projects and leaves a comment on the PR with the results.
- Ran the workflow https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/9007894138
- Triggered the creation of #703 and created the comment https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/pull/703#issuecomment-2101346767

Add script to check for outdated packages

---

.github/workflows/azure-remove-branch.yml
.github/workflows/continuous-deployment.yml
.github/workflows/e2e-test.yml
.github/workflows/reusable-database-deploy.yml
.github/workflows/reusable-e2e.yml
.github/workflows/sub-deploy-code-slot.yml
.github/workflows/sub-deploy.yml
ops/scripts/pipeline/az-cosmos-deploy.sh

Create Standalone E2e tests and properly handle E2E database and slot resource creation during deployment
- Addition of standalone e2e tests
- removal of automatic e2e database deletion for branches
- creation of slot resources on initial branch deployment
- deployed environment and ran tests through to verify tests run properly
Will need to merge this to main so I can make additional changes to the E2E standalone tests. Manual dispatch workflows are not able to be created outside the main branch

CAMS-397 E2E standalone test manual workflow and workflow testing resource updates

---

ops/git-setup/commit.template

We want to ensure that Sam gets credit for participating in ensembles.
Add Sam's no-reply email to the commit template.

Added Sam to commit message "Co-authored-by"

---

user-interface/src/data-verification/ConsolidationOrderAccordion.test.tsx
user-interface/src/data-verification/ConsolidationOrderAccordion.tsx

User must be able to reject a consolidation without entering a lead case or a consolidation type.
Removed requirement for lead case and consolidation type to be selected in order to reject a consolidation.
Also removed the need to have at least 2 cases selected to approve a rejection.
Test coverage is over 90%
This work does NOT include the validation component nor the logic to ensure that the user can not mark the case as the lead case when there is only 1 case on the order.  We will need to address this since, it is only a valid consolidation if there are at least 2 cases involved.  1 must be a lead case, and a different case must be a child.

CAMS-396 reject without type or lead and also without validation

---

.github/workflows/sub-security-scan.yml

We are experiencing an intermittent issue with the SAST Scan and Upload functionality.
Update to the latest version of the Veracode GitHub Action we are using.
Ran a few times with the new version with each scan succeeding. This does not guarantee the issue is fixed however.

Update Veracode action version

---

backend/functions/lib/testing/mock-gateways/mock-oauth2-gateway.ts
backend/functions/oauth2/mock-oauth2.function.ts

Provide a catch for misconfigured mock auth provider and meaningful error thrown when not in mock mode. 
try catch in mock-oauth function, override in forbidden message
N/A

added try catch for mock-oath2 function with more meaningful error

---

backend/functions/lib/adapters/gateways/okta/HumbleVerifier.ts

Remap the claim we get AD groups from Okta
Unit tests above threshold.

CAMS-406 - Remap Okta group claims to AD_Groups

---

docs/contributing/README.md

In order for developers to have the information they need when onboarding or setting up new development machines, we want to have documented all required steps.
Adds a section in the contributing portion of the docs addressing installing the Azure CLI and setting it up to use the Azure Gov tenant.

Add documentation of Azure CLI usage

---

.github/workflows/reusable-e2e.yml
.github/workflows/sub-build.yml

Downloading the build artifact uploaded by the newest version of the `actions/upload-artifact` Action failed.
Update the `actions/download-artifact` Action version to the latest.
[Run the full deployment](https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/10704818750).

Update to the latest upload-artifact action

---

backend/functions/lib/adapters/gateways/dxtr/offices.dxtr.gateway.test.ts
backend/functions/lib/adapters/gateways/dxtr/offices.dxtr.gateway.ts
backend/functions/lib/adapters/gateways/user-session-gateway.ts
backend/functions/lib/testing/mock-gateways/mock.offices.gateway.ts
backend/functions/lib/use-cases/offices/offices.gateway.interface.ts
common/src/cams/test-utilities/mock-data.ts

Return a list of offices per a given group designator
Changed the function that used to return a single office to return a list of offices.
Testing passes

CAMS-418 - Return a list of offices for a group designator

---

.github/workflows/sub-security-scan.yml
.github/workflows/veracode-sast-upload.yml

The upload and scan job occasionally breaks builds on main because only one such scan may be in progress at a time. We need to not run on every merge to main.
- Adds a new scheduled workflow (Mondays at 6 a.m. UTC) with the option to trigger manually.
- Removes the upload and scan from the continuous deployment workflow.
Workflow dispatch triggers cannot be run until after merge to main, so validation will be performed after the merge.

Extract sast upload scan to standalone workflow

---

backend/functions/lib/adapters/gateways/dxtr/offices.dxtr.gateway.ts

Fix the office lookup by group designator.
* Renamed the SQL parameter to match the placeholder in the SQL statement.
Manual integration test with Okta revealed the bug and showed it is now fixed.

CAMS-418 Fixed misnamed SQL parameter for office lookup

---

backend/functions/case-associated/case-associated.function.ts
user-interface/src/case-detail/CaseDetailScreen.tsx
user-interface/src/case-detail/panels/CaseDetailAssociatedCases.test.tsx
user-interface/src/case-detail/panels/CaseDetailAssociatedCases.tsx
user-interface/src/data-verification/consolidation/ConsolidationOrderAccordion.test.tsx
user-interface/src/lib/models/api.test.ts
user-interface/src/lib/models/api.ts
user-interface/src/lib/models/api2.test.ts
user-interface/src/lib/models/api2.ts
user-interface/src/search-results/SearchResults.tsx
user-interface/src/staff-assignment/modal/AssignAttorneyModal.tsx

We discovered some errors with the deployed application.
- associated cases function now correctly takes the `caseId` path param
- the frontend api can now handle 2xx responses with no payload
Automated tests were added/updated.

CAMS-356: Fix frontend handling of 201 and bad parameter

---

architecture/export-architecture-diagrams.sh
docs/contributing/README.md

We need to document how to keep the architecture diagrams up-to-date.
Add documentation about how to use the script that updates the architecture diagrams.

Document usage of the architecture diagram script

---

backend/functions/case-assignments/case.assignment.function.test.ts
backend/functions/case-associated/case-associated.function.test.ts
backend/functions/case-history/case-history.function.test.ts
backend/functions/case-summary/case-summary.function.test.ts
backend/functions/cases/cases.function.test.ts
backend/functions/consolidations/consolidations.function.test.ts
backend/functions/lib/controllers/attorneys/attorneys.controller.test.ts
backend/functions/offices/offices.function.test.ts
common/src/cams/test-utilities/mock-data.ts
user-interface/src/data-verification/DataVerificationScreen.test.tsx
user-interface/src/data-verification/consolidation/ConsolidationOrderAccordion.test.tsx
user-interface/src/data-verification/consolidation/consolidationOrderAccordionUtils.test.ts

We want our tests to provide good coverage while also reducing pain in writing them.
- Add tests for attorneys controller.
- Add and make use of mock data functions.
- Replace usage of `vitest.spyOn` with `vi.spyOn`.
Tests all pass and coverage increased.

CAMS-356: testing wrap up

---

backend/functions/lib/adapters/gateways/case.assignment.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/cases.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/cases.cosmosdb.repository.ts
backend/functions/lib/cosmos-humble-objects/fake.assignments.cosmos-client-humble.ts
backend/functions/lib/testing/local-data/local-cases-repository.ts
backend/functions/lib/testing/mock-data/case-history.mock.ts
backend/functions/lib/use-cases/case-assignment.ts
backend/functions/lib/use-cases/case-management.test.ts
backend/functions/lib/use-cases/orders/orders-consolidation-approval.test.ts
backend/functions/lib/use-cases/orders/orders.test.ts
backend/functions/lib/use-cases/orders/orders.ts
common/src/cams/assignments.ts
common/src/cams/auditable.ts
common/src/cams/history.ts
common/src/cams/test-utilities/mock-data.ts
user-interface/src/case-detail/panels/CaseDetailAuditHistory.test.tsx
user-interface/src/case-detail/panels/CaseDetailAuditHistory.tsx

Add common logging of `changedOn` and `changedBy` properties to audit records.

Cams 282 restrict data verification fritz

---

backend/functions/lib/use-cases/case-assignment.ts
backend/functions/lib/use-cases/orders/orders.ts
common/src/cams/auditable.ts

Orders sync fails when there is no session from a timer function
Corrected logic in audit record creation when a session/user does not exist.
Tests are working

CAMS-282 Fixed logic error when loading orders without session

---

.github/workflows/sub-deploy-code-slot.yml

workflow did not enable access after slot swap, it worked previously because we retained the access policies that have been unchanged for some time
- added enable access step to the end of deployment
- ran workflow deployment

added enable access post-swap

---

ops/git-setup/commit.template

We want to keep the commit template up-to-date.
Remove Sam from the list of co-authors.

Remove Sam from co-authored list

---

.github/workflows/continuous-deployment.yml

To provide more confidence in dependency updates, we want to run the full deployment.
Add the `dependency-updates-auto` branch name to the condition for running the deployment.

Add dependency-updates-auto to deployment

---

backend/functions/lib/use-cases/case-assignment.ts
backend/functions/lib/use-cases/orders/orders.ts
common/src/cams/auditable.ts
docs/architecture/decision-records/Auditable.md

We want to document the reason for the creation and proper use of `auditable.ts`.
Add an ADR.

Cams 282 auditable

---

backend/functions/lib/adapters/gateways/storage/local-storage-gateway.ts
backend/functions/lib/adapters/gateways/storage/ustp-office-data-map.ts
backend/functions/lib/adapters/types/storage.ts
backend/functions/lib/adapters/types/ustp-office-data-map.ts
common/src/cams/courts.ts
common/src/cams/session.test.ts
common/src/cams/session.ts
common/src/cams/users.ts
ops/cloud-deployment/params/ustp-cams-cosmos-containers.parameters.json

We want to update the data modeling to enable other goals for CAMS-283.
- add roles to CamsUserReference
- add types to properly model USTP Office to court relationship
- add data for Seattle and New York offices
- add Cosmos DB container definition for offices
Automated tests pass.

CAMS-283: update model

---

backend/functions/lib/adapters/gateways/dxtr/case-docket.mock.gateway.ts
backend/functions/lib/adapters/gateways/okta/okta-user-group-gateway.test.ts
backend/functions/lib/adapters/gateways/okta/okta-user-group-gateway.ts
backend/functions/lib/adapters/types/authorization.ts
backend/functions/lib/configs/application-configuration.ts
backend/functions/lib/configs/user-groups-gateway-configuration.ts
backend/functions/lib/factory.ts
backend/functions/lib/testing/isolated-integration/test-okta-group-api.ts
backend/functions/package-lock.json
backend/functions/package.json
common/src/cams/users.ts

Get group membership information from Okta.
* added UserGroupGateway interface
* implemented OktaUserGroupGateway implementing UserGroupGateway
* 100% test coverage for OktaUserGroupGateway
* Tested the adapter against the Flexion dev instance of Okta

CAMS-283 - Okta adapter

---

backend/functions/lib/adapters/gateways/cases.cosmosdb.repository.ts
backend/functions/lib/adapters/gateways/consolidations.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/consolidations.cosmosdb.repository.ts
backend/functions/lib/adapters/gateways/cosmos/cosmos.repository.test.ts
backend/functions/lib/adapters/gateways/cosmos/cosmos.repository.ts
backend/functions/lib/adapters/gateways/offices.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/offices.cosmosdb.repository.ts
backend/functions/lib/controllers/offices/offices.controller.test.ts
backend/functions/lib/controllers/offices/offices.controller.ts
backend/functions/lib/factory.ts
backend/functions/lib/testing/mock-gateways/mock-attorneys.gateway.ts
backend/functions/lib/use-cases/attorney.gateway.interface.d.ts
backend/functions/lib/use-cases/attorneys.test.ts
backend/functions/lib/use-cases/attorneys.ts
backend/functions/lib/use-cases/gateways.types.ts
backend/functions/lib/use-cases/offices/offices.test.ts
backend/functions/lib/use-cases/offices/offices.ts
backend/functions/offices/offices.function.ts
backend/functions/package.json
common/package.json
common/src/api/search.ts
common/src/cams/test-utilities/attorneys.mock.ts
user-interface/package.json
user-interface/src/lib/models/api2.ts

We need to be able to get the list of attorneys who work in an office.
We extend the offices endpoint to retrieve staff from a new CosmosDB container.
Deployed the branch and verified that the api does return data from the container.

CAMS-283: Retrieve attorneys by office

---

backend/functions/orders-manual-sync/orders-manual-sync.function.ts
common/src/cams/auditable.ts
common/src/cams/test-utilities/mock-data.ts
common/src/cams/test-utilities/offices.mock.ts
dev-tools/test-data/utility.ts
user-interface/src/lib/models/api.ts
user-interface/src/lib/models/api2.ts

When we have JSDocs, it is most helpful if they properly follow the syntax.
- Move types to their proper place in `@param` tags.
- Add `@return` tags where needed.
- Add `@template` tags where generics are used.
- Add stronger typing to `api2.ts` interface and functions as the JSDoc actually caused build failures without these changes.
Ran build successfully.

Fix jsdocs

---

backend/functions/jest.config.js
backend/functions/lib/adapters/gateways/consolidations.cosmosdb.repository.ts
backend/functions/lib/adapters/gateways/cosmos/cosmos.repository.ts
backend/functions/lib/adapters/gateways/offices.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/offices.cosmosdb.repository.ts
backend/functions/lib/testing/isolated-integration/test-okta-group-api.ts
backend/functions/lib/testing/local-data/local-cosmos-db-repository.ts
backend/functions/lib/use-cases/gateways.types.ts
backend/functions/lib/use-cases/offices/offices.ts
common/src/cams/staff.ts

Add office staff to offices repo
* Added `syncOfficeStaff` function to offices use case
* Function gets groups and users from the IdP
* Function maps groups to roles and offices
* Function writes staff records to the office repo

CAMS-283 - Add syncOfficeStaff to Offices use case

---

backend/functions/lib/adapters/gateways/runtime-state.cosmosdb.repository.ts
backend/functions/lib/use-cases/gateways.types.ts
backend/functions/lib/use-cases/offices/offices.ts
ops/cloud-deployment/backend-api-deploy.bicep

update cosmos with office staff sync state
- use upsert within runtime state repo
- add OFFICE_STAFF_SYNC_STATE document type
- update backend env vars with new conf
- ran locally
- deployed ENV
We have updated the staging and prod environment with the new keyvault secret references

CAMS-283 update cosmos with office staff sync state

---

backend/functions/lib/adapters/gateways/offices.cosmosdb.repository.test.ts
backend/functions/lib/adapters/gateways/offices.cosmosdb.repository.ts
common/src/cams/staff.ts

Add TTL to office staff records
* Moved OfficeStaff document type to the backend from common
* Added ttl property to the OfficeStaff type.
* Added 75 minute TTL to all OfficeStaff documents written to Cosmos.
Tests pass

CAMS-283 - Add TTL to OfficeStaff documents

---

backend/functions/azure/application-context-creator.test.ts
backend/functions/azure/application-context-creator.ts
backend/functions/lib/adapters/gateways/okta/okta-gateway.test.ts
backend/functions/lib/adapters/gateways/okta/okta-gateway.ts
backend/functions/lib/adapters/types/authorization.ts
backend/functions/lib/adapters/utils/session-gateway.ts
backend/functions/lib/factory.ts
backend/functions/lib/testing/mock-gateways/mock-oauth2-gateway.ts
backend/functions/lib/testing/mock-gateways/mock-user-session-use-case.ts
backend/functions/lib/use-cases/user-session/user-session.test.ts
backend/functions/lib/use-cases/user-session/user-session.ts

Use both ad_groups and groups claims for groups from Okta users
* Refactored UserSessionGateway into UserSessionUseCase
* Merged the ad_groups and groups claims into a single group set.
Added tests for unifying the ad_groups and groups claims

CAMS-446 - Okta ad group bug

---

backend/functions/lib/adapters/gateways/okta/okta-gateway.test.ts
backend/functions/lib/adapters/gateways/okta/okta-gateway.ts

Catch all variations on the case of the ad_groups property.
Tested more than one case variation of ad_groups property in unit test.

CAMS-446 - Refactor logic to get any case variation of ad_groups

---

backend/functions/lib/use-cases/offices/offices.ts
user-interface/src/lib/models/api2.ts
user-interface/src/lib/utils/local-cache.test.ts
user-interface/src/lib/utils/local-cache.ts

Add local cache capability to UI. Cache attorney responses from API.
* Added LocalCache to add expirations to items in the browser local storage.
* Added generic cache handling logic to API2.
* Used generic cache handling logic for getOfficeAttorneys.
Manually tested.

CAMS-283 - generic UI cache

---

ops/cloud-deployment/backend-api-deploy.bicep

Jira ticket: CAMS-283
hyphens not allowed in Azure app config settings, replaced with underscores
hyphens not allowed in Azure app config settings, replaced with underscores within OKTA_API_KEY
N/A
N/A

CAMS-283 corrected app setting name for OKTA_API_KEY

---

backend/functions/lib/factory.ts
backend/functions/lib/testing/mock-gateways/mock-offices.repository.test.ts
backend/functions/lib/testing/mock-gateways/mock-offices.repository.ts
backend/functions/lib/use-cases/offices/offices.test.ts

Support getting office attorneys when in mock user auth mode.
* Added MockOfficesRepository
Tested that the mock repo returned Manhattan attorneys from the mock users file.

CAMS-283 - Add MockOfficesRepository

---

test/e2e/playwright/consolidation-orders.spec.ts
test/e2e/playwright/transfer-orders.spec.ts

We need to update the e2e tests to wait for calls to `courts` instead of `offices`.
Update e2e tests to reflect change from using offices endpoint to using courts.
Validated locally and on a full deployment of the branch.

CAMS-283: fix e2e

---

docs/operations/_sidebar.md
docs/operations/e2e-tests.md

Provide developers documentation for running e2e tests locally
- added e2e-tests.md outlining running end to end tests locally
N/A

CAMS-283: e2e documentation

---

backend/functions/azure/functions.test.ts
backend/functions/lib/adapters/gateways/mongo/offices.mongo.repository.test.ts
backend/functions/lib/adapters/gateways/mongo/offices.mongo.repository.ts
backend/functions/lib/adapters/gateways/mongo/orders.mongo.repository.ts
backend/functions/lib/adapters/gateways/mongo/utils/mongo-adapter.test.ts
backend/functions/lib/adapters/gateways/mongo/utils/mongo-adapter.ts
backend/functions/lib/controllers/cases/cases.controller.test.ts
backend/functions/lib/controllers/offices/offices.controller.test.ts
backend/functions/lib/controllers/orders/orders.controller.test.ts
backend/functions/lib/use-cases/offices/offices.test.ts
backend/functions/lib/use-cases/offices/offices.ts
ops/cloud-deployment/lib/cosmos/mongo/cosmos-collections.bicep
user-interface/src/lib/models/api2.test.ts

We want to improve test coverage.
Describe what has changed.

CAMS-442 test coverage

---

ops/cloud-deployment/lib/cosmos/mongo/cosmos-account.bicep

Jira ticket: CAMS-451
add azure portal access to cosmos during deployment
corrected cosmos middleware Ips and removed 0.0.0.0 for security
deploy*

CAMS-451 corrected middleware Ips for cosmos

---

backend/functions/lib/adapters/gateways/mongo/offices.mongo.repository.test.ts
user-interface/src/login/Session.test.tsx
user-interface/src/login/Session.tsx

Preload office staff on login
* Async called get office staff endpoint upon login in Session component
Unit tests

CAMS-478 - Prefetch office staff and cache on login

---

user-interface/src/lib/humble/broadcast-channel-humble.ts
user-interface/src/login/Login.tsx
user-interface/src/login/SessionEnd.tsx
user-interface/src/login/broadcast-logout.test.ts
user-interface/src/login/broadcast-logout.ts
user-interface/vitest.config.mts

Logout of all windows/tabs when a user logs out of the app in a tab/window.
- Added event listener to broadcast channel in each window/tab.
- Broadcast logout event over the channel to all windows/tabs.
- Manual testing
- Humble object unit testing

CAMS-476 - Add broadcast logout functionality

---

user-interface/src/lib/components/Header.tsx
user-interface/src/lib/components/cams/DropdownMenu/DropdownMenu.tsx

Add Help menu link to document to the user dropdown menu
Added link to menu with cams_help browser tab target.  Link goes to sharepoint site.
No testing needed.  Already covered.  Manual testing works.
n/a

CAMS-440: Added help document to user dropdown menu

---

user-interface/src/case-detail/CaseDetailScreen.tsx
user-interface/src/case-detail/panels/CaseDetailCourtDocket.test.tsx
user-interface/src/case-detail/panels/CaseDetailCourtDocket.tsx
user-interface/src/case-detail/panels/CaseDetailOverview.tsx
user-interface/src/lib/components/uswds/Input.test.tsx
user-interface/src/lib/components/uswds/Input.tsx
user-interface/src/lib/components/uswds/forms.scss

Address Case Details Non-critical Accessibility Issues (Part 2)
This ticket handles the accessibility issues that are not mandated by WCAG.
Case Overview
-  When a case is unassigned, the Assigned Staff List field gets in a state where an unordered list has a direct child that is a span, which threw an error in Axe DevTools.
Court Docket View
-  Change Document Number field to simple text entry, and use real-time validation to inform the user that only numbers are acceptable. [input="number"] should generally be avoided, because it poses accessibility issues in terms of informing the user that certain inputs are valid or not.
-  When there is a blank docket entry number (e.g. two entries on the same day), Axe DevTools throws an error, stating that a div has an aria-label attribute, but no …

CAMS-437 case details accessibility

---

backend/functions/office-staff-sync/office-staff-sync.function.ts

Jira ticket: CAMS-484
Change when the office staff sync runs to avoid overloading Okta at inopportune times.
Schedule. That's all.

CAMS-484 - Change the office staff sync execution time

---

ops/scripts/pipeline/slots/az-slot-start-stop-operations.sh

Jira ticket: CAMS-484
improperly named resourceGroup parameter for slot operations script
renamed resource-group parameter to resourceGroup
ran it locally
N/A

CAMS-484 corrected param name

---

user-interface/src/case-detail/panels/CaseDetailAuditHistory.tsx

Jira ticket: CAMS-488
Case Assignment History with a null in before or after was causing uncaught errors
- created a function to validate the assignments.before/after and properly handle those in the JSX
- ran locally and verified
N/A

CAMS-488 corrected the value operator for assignmentHistory

---

.github/workflows/azure-remove-branch.yml
ops/scripts/utility/check-env-hashes.sh

It can be frustrating to figure out what branch a deployed environment belongs to for determining whether we still need it.
Adds a utility script which can be used to find a deployed environment's branch by it's short hash.
Ran the script, validating behavior using currently deployed branches.
Further improvements might include things like taking multiple existing short hashes to find multiple branches in one run.

CAMS-461 cleanup helper script

---

.github/workflows/azure-remove-branch.yml
ops/scripts/utility/az-delete-branch-resources.sh
ops/scripts/utility/check-env-hashes.sh

e2e test databases were not being deleted—or at least not always—when the clean up script was run.
Modifies the clean up script to delete the e2e test database.
Added logging of whether the resources exist to the check-env-hashed script.
Ran locally as expected.
Ran the workflow against the deployed environment. https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/actions/runs/12381595212
The number of required inputs is a bit high. We may want to find a way to support environment variables for local running.

Use existing shell script to delete database

---

backend/lib/adapters/gateways/dxtr/offices.dxtr.gateway.test.ts
backend/lib/adapters/gateways/dxtr/offices.dxtr.gateway.ts
backend/lib/testing/isolated-integration/test-acms-migration.ts
backend/lib/testing/isolated-integration/test-office-names.ts
backend/lib/testing/isolated-integration/test-okta-group-api.ts
backend/lib/use-cases/offices/offices.ts
test/e2e/playwright/consolidation-orders.spec.ts

Fix invalid division code lookup for offices
* Changed USTP office name lookup to not throw an exception but rather return a place holder name
* Added the bad division code to the list of divisions to omit from the office list
* Unit test updated
* Manual testing

CAMS-482 - Fix invalid division code lookup for offices

---

.github/workflows/continuous-deployment.yml
.github/workflows/update-dependencies.yml

properly trigger deployment on npm updates auto branch
- addition o workflow-dispatch step
- ran dependency updates auto and verified continuous-deployment.yml was triggered with correct inputs
Note: GITHUB_TOKEN auth does not trigger workflow builds in any aspects to prevent infinite looping of workflows. So we have to explcitly call

Dependency update fix

---

backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts
backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts

Jira ticket: CAMS-492
Case search only worked with chapter 15 cases properly, because by default we pushed chapter 15 into the predicate
- modified query params to only push  chapters when we have predicate.chapters available
ran locally
we might want to push a default set of chapters as the params rather than not querying for them at all like ['7', '9', '11', '12', '13', '15']

CAMS-492 Case Search Bug

---

.pre-commit-config.yaml
backend/eslint.config.mjs
common/eslint-test.config.mjs
common/eslint.config.mjs
dev-tools/eslint.config.mjs
eslint.config.mjs
package-lock.json
package.json
test/e2e/eslint.config.mjs
user-interface/eslint-ui-test.config.mjs
user-interface/eslint-ui.config.mjs
user-interface/eslint.config.mjs
user-interface/package-lock.json
user-interface/package.json
user-interface/src/data-verification/DataVerificationScreen.test.tsx
user-interface/src/data-verification/consolidation/ConsolidationOrderModal.test.tsx
user-interface/src/lib/components/combobox/ComboBox.test.tsx
user-interface/src/lib/components/uswds/DatePicker.test.tsx
user-interface/src/lib/utils/caseNumber.test.ts
user-interface/src/test/staff-assignment.test.tsx

We want to use the `testing-library` package as intended most of the time.
- Add the eslint plugin provided by the package authors.
- Configure the default rules leaving some turned off for further consideration before enabling.
- Correct new linting errors.
Automated tests still pass.
We could still add the [vitest plugin](https://www.npmjs.com/package/@vitest/eslint-plugin).

Add testing library linting

---

user-interface/src/staff-assignment/screen/StaffAssignmentScreen.test.tsx
user-interface/src/staff-assignment/screen/StaffAssignmentScreen.tsx

The staff assignment screen should only look for cases for enabled chapters which means 15 by default and 11 and/or 12 if the feature flags are turned on.
We modify the search predicate to only include chapter 15 by default and other chapters if enabled by feature flag.
Automated tests modified to test this.

CAMS-492: Only get chapter 15 and enabled chapters

---

backend/lib/adapters/gateways/mongo/consolidations.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/consolidations.mongo.repository.ts

During order sync, we call `insertMany` from the Mongo adapter for consolidations even if there is nothing to insert.
Bail early if the list is empty, undefined, or null.
Added automated tests.

CAMS-496: Do not call insertMany for empty or falsy list

---

backend/lib/adapters/gateways/mongo/user-session-cache.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/user-session-cache.mongo.repository.ts

User sessions are not being persisted.
We call the `replaceOne` method with the `upsert` flag set to true.
Updated test.

CAMS-497: Set upsert flag on session repo replaceOne method

---

backend/lib/adapters/gateways/mongo/utils/mongo-adapter.test.ts
backend/lib/adapters/gateways/mongo/utils/mongo-adapter.ts

Mongo adapter was not throwing when replaceOne found no matching items.
Extend logic to cover error cases more explicitly.
Update automated tests.

CAMS-498: Throw errors if replaceOne does not persist

---

ops/cloud-deployment/main.bicep

We have to modify CORS settings and stop and start the Function App to trigger the sync.
Add Azure Portal url to the CORS allowlist so that we can just trigger Functions when needed.

Add Azure Portal url to CORS allowlist

---

backend/function-apps/api/admin/admin.function.test.ts
backend/function-apps/api/admin/admin.function.ts
backend/lib/adapters/gateways/mongo/offices.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/offices.mongo.repository.ts
backend/lib/controllers/admin/admin.controller.test.ts
backend/lib/controllers/admin/admin.controller.ts
backend/lib/factory.ts
backend/lib/testing/mock-gateways/mock-mongo.repository.ts
backend/lib/use-cases/admin/admin.test.ts
backend/lib/use-cases/admin/admin.ts
backend/lib/use-cases/gateways.types.ts
backend/lib/use-cases/offices/offices.test.ts

We need project team members to be able to validate privileged functionality in staging.
Adds two new admin Functions to create and delete staff entries.
- Automated tests added.
- Will verify with a dev deployment.
I think an admin portal would be really good to add. Currently these new functions would have to be run by someone with elevated access within the Azure Portal. An admin screen in CAMS could leverage role based access meaning non-developers would be able to run them.

CAMS-500: enable roles in staging

---

backend/lib/adapters/gateways/mongo/offices.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/offices.mongo.repository.ts
backend/lib/use-cases/admin/admin.test.ts
backend/lib/use-cases/admin/admin.ts

Upsert if failing for staff documents.
We temporarily set the ttl to 23 hours so that the documents will be removed by the next night when the sync runs. This way each night at midnight eastern, the container should be empty and the sync should succeed.
Updated automated tests.

Set default ttl to 23 hours temporarily

---

backend/lib/adapters/gateways/mongo/case-assignment.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/case-assignment.mongo.repository.ts
backend/lib/adapters/gateways/mongo/offices.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/offices.mongo.repository.ts
backend/lib/adapters/gateways/mongo/runtime-state.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/runtime-state.mongo.repository.ts
backend/lib/adapters/gateways/mongo/user-session-cache.mongo.repository.test.ts
backend/lib/adapters/gateways/mongo/utils/mongo-adapter.test.ts
backend/lib/adapters/gateways/mongo/utils/mongo-adapter.ts
backend/lib/controllers/admin/admin.controller.test.ts
backend/lib/controllers/admin/admin.controller.ts
backend/lib/factory.ts
backend/lib/testing/mock-gateways/mock-mongo.repository.ts
backend/lib/testing/mock-gateways/mock.offices.repository.ts
backend/lib/use-cases/admin/admin.test.ts
backend/lib/use-cases/admin/admin.ts
backend/lib/use-cases/gateways.types.ts
backend/lib/use-cases/offices/offices.test.ts
backend/lib/use-cases/offices/offices.ts

Upserts that modify documents are incorrectly identified as having failed.
Properly identify modified count as an indicator of success for upserts. Extend the ttl back out past 24 hours to ensure that documents exist at least until the next sync runs.
Updated all related automated tests. Also exercised the endpoint to ensure that upserts and replacements work.

CAMS-502: Properly handle modified result for upserts

---

backend/lib/adapters/utils/feature-flag.ts
common/src/feature-flags.test.ts
common/src/feature-flags.ts
user-interface/src/lib/hooks/UseFeatureFlags.test.ts
user-interface/src/lib/hooks/UseFeatureFlags.ts

We do not want to default to features being turned on simply to ensure that a11y tests can validate features that are behind flags.
- Only return feature flag values as true by default if we are testing.
- Updated automated tests.
- Validated locally in the following scenarios:
- Valid client id for Launch Darkly.
- Invalid client id for Launch Darkly.
- `CAMS_PA11Y` set to true.
- `CAMS_PA11Y` set to false and no client id for Launch Darkly.
This will also prevent the behavior we see on refresh where a Case Assignment Manager who refreshes the screen while viewing the Staff Assignment screen will see chapter 11 cases despite that feature flag being turned off.

CAMS-302: Only use default flag values for testing

---

backend/lib/adapters/gateways/dxtr/offices.dxtr.gateway.ts
backend/lib/adapters/gateways/okta/okta-user-group-gateway.test.ts
backend/lib/adapters/gateways/okta/okta-user-group-gateway.ts
backend/lib/testing/analysis/acms-dxtr-divisions/compare-divisions.ts
backend/lib/testing/analysis/export-office-csv.ts
backend/lib/testing/mock-gateways/mock-user-group-gateway.ts
backend/lib/use-cases/admin/admin.test.ts
backend/lib/use-cases/admin/admin.ts
backend/lib/use-cases/offices/offices.ts
backend/lib/use-cases/users/users.helpers.test.ts
backend/lib/use-cases/users/users.helpers.ts
common/src/cams/courts.test.ts
common/src/cams/offices.ts
common/src/cams/test-utilities/mock-data.ts

User's assigned offices are not being added to their session.
Use the Okta group name rather than identifier to match offices.
Ran locally against dev instance of Okta and updated tests. Will validated in staging prior to production deployment.

CAMS-512: Properly identify user's offices

---

.github/workflows/azure-remove-branch.yml
.github/workflows/reusable-database-deploy.yml

The branch resource cleanup also needed to transition to an azcli step. it was failing because of AZCLI commands within a script executing actions on cosmosdb
- convert deletion step of branch cleanup to azcli action
ran through pipeline

converted delete branch resources to azcli task

---

.github/workflows/reusable-sca-scan.yml

SCA scan started failing this morning seemingly because of versioning issues with Gov Cloud, Still need RCA
- upgrade SCA scan step to 2.1.12
pipeline validation

updated SCA scan step version

---

ops/scripts/utility/az-delete-branch-resources.sh

az-delete-branch-resources.sh was failing when we didn't have an e2e database present but other resource groups were. This would be problematic in cases where a database was not deployed and a branch was merged and not exactly the behavior we want
- update script to not fail on missing e2e database and output the message from the script when one doesnt exist
- ran deletion workflow

correct logic within delete-branch-resources.sh

---

user-interface/src/lib/hooks/UseOutsideClick.ts

Bug Fix for -- comboBox outside click action was swallowing up the click event, such that if a user has the comboxOpen, and then clicks on a button, the comboBox closes but the button click is not handled.
Adjusted the UseOutsideClick hook to handle a "mousedown" event rather than a "click" event.
Manually tested using mouse and verified that keyboard interaction still works as expected.

CAMS-516 UseOutsideClick now acts on mousedown, not click

---

.github/workflows/azure-remove-branch.yml
.github/workflows/reusable-backend-slot.yml
.github/workflows/reusable-build-frontend.yml
.github/workflows/reusable-build-info.yml
.github/workflows/reusable-deploy.yml
.github/workflows/reusable-e2e.yml
.github/workflows/reusable-endpoint-test.yml
.github/workflows/reusable-frontend-slot.yml
.github/workflows/sub-deploy-code-slot.yml
.github/workflows/sub-deploy-code.yml
.github/workflows/sub-security-scan.yml
ops/cloud-deployment/ustp-cams-cosmos.bicep
ops/scripts/pipeline/az-cosmos-deploy.sh
ops/scripts/pipeline/slots/az-func-slot-deploy.sh

when working with an error we were seeing related to deployment of the users collection, I noticed there was an opportunity to streamline the deployment workflow for the cosmos e2e database and push it into one template and simplify the process. to keep us up to date I also switched all of our az/login GHA usages to v2 instead of v1
- update all azure/login@v1 to v2
- minimize and simplify cosmos database deployment bicep
- ran through pipeline and tested deployment of database
- I left branchHaseId in the cosmos deployment script for now to avoid having to update USTP but we can remove it and pass in the already generated name to the script if we choose to.

Cosmos Database Deployment and bicep Updates

---

backend/lib/adapters/gateways/cases.local.gateway.ts
backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.test.ts
backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts
backend/lib/testing/isolated-integration/test-dxtr-tx-bisect.ts
backend/lib/use-cases/cases/cases.interface.d.ts
backend/package.json

Find AO_TX transaction ID range by date
Added binary search of the AO_TX table to find starting and ending TX_ID bounds by ISO date string.
Manual testing

CAMS-421 Find AO_TX transaction ID range by date

---

ops/cloud-deployment/ustp-cams-cosmos.bicep

We needed to default the value for cosmosE2eDatabaseName so we did not require the param in USTP yet
default param to empty string in bicep
N/A
N/A 
-once we implement E2E testing in USTP this will change

default e2e db name to empty string to prevent failure in USTP

---

backend/function-apps/dataflows/dataflows-common.test.ts
backend/function-apps/dataflows/dataflows-common.ts
backend/function-apps/dataflows/import/import-dataflow.ts
backend/function-apps/dataflows/migration/client/acms-migration-trigger.function.ts
backend/lib/adapters/types/http.d.ts
backend/lib/use-cases/acms-orders/acms-orders.ts

Ensure import triggers are not maliciously triggered.
Added guards to triggers to return Unauthorized response if called without a correct API key.
Unit test coverage for the isAuthorized function.

CAMS-421 Protect import HTTP triggers with API key

---

backend/lib/controllers/case-notes/case.notes.controller.test.ts
common/src/cams/sanitization.test.ts
common/src/cams/sanitization.ts
user-interface/src/lib/models/api2.test.ts
user-interface/src/lib/models/api2.ts

Jira ticket: CAMS-522
We were seeing an issue where normal words were being rejected and not saved with notes. 
- The JAVACSRIPT regex was causing issues within the sanitization. I temporarily commented it out until we figure out what we actually want to put there.
- The rejection post calls were also doing an odd order of operations for valid user input and sanitization that was oppposite of the way we really wanted. So That was fixed as well
- updated unit tests validating the change
- ran locally and verified
to get this nailed down we just need to decide what goes into the JAVASCRIPT regex and wrap up the tests for it

CAMS-522 fixed Regex on isValidUserInput 

---

backend/function-apps/dataflows/dataflows-common.ts
backend/function-apps/dataflows/import/migrate-cases.ts

Allow the migration to run without passing an invocationId.
* Removed invocationId from start message.
* Removed guard requiring invocationId to be on the start message.
Manual test

CAMS-421 Remove unnecessary passing of invocationId on start

---

user-interface/src/lib/components/Header.tsx
user-interface/src/lib/hooks/UseFeatureFlags.ts

Admin users should have the ability to set a System Maintenance message and display a banner.
This is handled with a flag.  To set a message, change the "Enabled" variation of the flag and then enable the flag to display the banner.

CAMS-529 system maintenance banner

---

backend/function-apps/dataflows/import/migrate-cases.ts

The production service account cannot truncate the migration table.
We skip the attempt to truncate the migration table.
Automated tests still pass. This is just housekeeping that will have to be performed manually.

Skip attempt to truncate migration table

---

backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts

Use ACMS caseIds for case sync
Altered SQL query in DXTR to use the ACMS division code from AO_CS_DIV when constructing caseIds.
Manual

CAMS-421 Return ACMS caseId for caseIds to sync

---

backend/lib/adapters/services/logger.service.test.ts
backend/lib/adapters/services/logger.service.ts
common/src/cams/test-utilities/mock-data.ts

We want to prevent PII from being logged in the `message` parameter of the logger functions.
- Add scrubbing of the `message` parameter which uses a regex/replace to identify potential tax identifiers and replace them with `[REDACTED]`.
- Add `ein` and `itin` to the disallowed list just in case these are ever encountered in data we are logging.
- Updated automated tests.
I was considering adding a maximum length of the message string to prevent us from putting entire objects in the message. This is not strictly necessary given the new scrubbing, but realistically the message should not be a stringified json object. We can do this with the future ticket to clean up logging if we choose to.

CAMS-421: Scrub potential tax identifiers from message

---

backend/lib/adapters/gateways/debtor-type-gateway.test.ts
backend/lib/adapters/gateways/debtor-type-gateway.ts
backend/lib/adapters/gateways/dxtr/cases.dxtr.gateway.ts
backend/lib/adapters/gateways/petition-gateway.test.ts
backend/lib/adapters/gateways/petition-gateway.ts

Sync cases without petition or debtor types
* Left join on the AO_TX table so case summaries are returned even if the type=1, code=1 TX records are absent.
* Update the label mappings to handle null codes for petition and debtor type codes.
* Unit testing
* Manual testing

CAMS-421 Handle missing TX join

---

.github/workflows/reusable-database-deploy.yml
ops/scripts/pipeline/slots/az-app-slot-deploy.sh

The path where the zip file is located in the USTP runner is not handled the same way as it is in GitHub Actions.
Instead of `pushd`ing into the directory where we then unzip the file and check for the git sha, we now do everything from the runner's default directory.
Ran a successful deployment in staging.
This also includes a workaround for a problem with the Azure CLI version now in use by the GitHub Actions runners. https://github.com/Azure/azure-cli/issues/31419#issuecomment-2858720156

CAMS-389: Fix staging deploy
